### ISSUE TITLE
Consider uploading Chromium WebVR builds as GitHub Releases

### ISSUE THREAD

**Issue by cvan** [toji/chrome-webvr-issues#102]
Instead of using the [Google Drive folder](https://drive.google.com/embeddedfolderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ#list), perhaps it's worth repurposing this repo for hosting all the releases. GitHub Releases let you do nice Markdown release notes, so that'd be awesome to see next to each downloadable build (and then you could forgo this separate [Google Doc for the Release Notes](https://docs.google.com/document/d/1Uixn8q9_iuIEIwAFzBXxebaIrbGREgXEE0r7SrBHhTM/edit)). Thoughts?

**Comment by toji** [comment]
Not a bad idea! Do you know if they have a nice embedding method?

**Comment by cvan** [comment]
> Not a bad idea! Do you know if they have a nice embedding method?

The [GitHub API for Releases](https://developer.github.com/v3/repos/releases/) is quite easy to use. I've worked with the GitHub API in the past, and to avoid throttling (if the same anonymous user keeps refreshing the page, causing a bunch of requests) I've used IndexedDB and localStorage when doing XHR/`fetch` requests if I'm doing it on the client side. Or, in the past, I've had a simple `npm` command that would do a build step (possibly on a GitHub Webhook when a new Release is triggered) to regenerate the HTML document to create an index based on the responses from the GitHub API requests.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
