### ISSUE TITLE
Projection matrices are wrong

### ISSUE THREAD

**Issue by pdaehne** [toji/chrome-webvr-issues#104]
The code for calculating the projection matrices is wrong. The current code maps depthNear and depthFar to 0 and 1, it should be -1 and 1 for OpenGL. It does not make much difference visually, but you loose half of the depth buffers precision. The wrong code is in the file "VRFrameData.cpp", function "projectionFromFieldOfView", when calculating components 10 and 14 of the matrix. The correct code is:

out[10] = (depthNear + depthFar) / (depthNear - depthFar);
out[14] = (2 * depthFar * depthNear) / (depthNear - depthFar);

Have a look into the WebVR Spec 1.0, it had the correct code before the update to WebVR 1.1.

**Comment by toji** [comment]
Good catch, thanks. I must have pulled the math from a stale file. I won't have a chance to update this for a week or so, but I'll make sure to get on this as soon as I can.

**Comment by toji** [comment]
Being addressed in https://codereview.chromium.org/2407413002/
