### ISSUE TITLE
vrDisplay.submitFrame() crashes if pose is not available

### ISSUE THREAD

**Issue by simonThiele** [toji/chrome-webvr-issues#107]
I'm working with HTC Vive and the current newest chrome-webvr-build on windows. The browser crashes with `aw snap` when calling `vrDisplay.submitFrame();` right at the moment when the Vive is facing away from the tracking cameras, so the getPose(); method is returning only null values.

My workaround atm is manually getting the pose and injecting as optional parameter:

``` javascript
var pose = vrDisplay.getPose();
if ( pose && pose.position ) {
  vrDisplay.submitFrame(pose);
}
```

**Comment by Noxalus** [comment]
Same issue here with the Oculus Rift CV1, your workaround also allow me to avoid this crash, thanks.

**Comment by capnmidnight** [comment]
I don't have time to test this right now, but I believe it would be better to keep track of the most recent, non-null pose value and submit a frame using that, rather than skipping submitting a frame when there is no current pose. It seems like it will play nicer with Asynchronous Time Warp.

**Comment by swomack** [comment]
` vrDisplay.submitFrame(pose);` crashes even if we submit the frame with most recent not-null pose value.

**Comment by axinging** [comment]
Can anyone help to provide a full test for this crash issues?
I didn't think vrDisplay.submitFrame(pose)  works,   submitFrame accepts no parameter.
As to why simonThiele works, I guess it is because vrDisplay.getPose(), which can update pose in VRDisplay

**Comment by simonThiele** [comment]
@axinging sure it does take the pose param as optional: https://developer.mozilla.org/en-US/docs/Web/API/VRDisplay/submitFrame

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
