### ISSUE TITLE
Polyfill prevented from working, causing error on Chromium without HMD attached

### ISSUE THREAD

**Issue by tbalouet** [toji/chrome-webvr-issues#108]
With the latest webvr-manager, using Chromium without any HMD plugged in the computer makes an error on line 59:

```
Uncaught (in promise) TypeError: Cannot read property 'isPolyfilled' of null
    at WebVRManager.<anonymous> (webvr-manager.js:59)
(anonymous) @ webvr-manager.js:59
```

It's because the polyfill isn't called, because navigator.getVRDisplays exists. But as there's no HMD plugged in, the manager crashes, preventing from having a basic desktop experience.

Even he doesn't have the last version, you can try it out on this page:
https://www.clicktorelease.com/code/polygon-shredder/vr/

Copy of the bug is wrote out to the webvr boilerplate, as I don't know who should be in charge:
https://github.com/borismus/webvr-boilerplate/issues/161

With Chromium Version 55.0.2869.0 (64-bit) on Windows 10.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
