### ISSUE TITLE
Getting really long hangs when starting.

### ISSUE THREAD

**Issue by caseyyee** [toji/chrome-webvr-issues#109]
Sometimes I will need to wait for 20-30 seconds before the browser starts.   Last two builds (1.1, and 1.0 versions) seem to exhibit this same issue.

**Comment by Prof-Abbott** [comment]
Yes, same here. With the Oct 29 build I get lots more weird warnings in the Dev console like "Request was blocked by DevTools" never happened before. Also I don't recall seeing a SW registered message before that appears on startup. Looking at memory and CPU, nothing much happens for 20s or so then it gradually ramps up and Chrome appears

**Comment by jbaicoianu** [comment]
I've been seeing this for a few months as well, just took about a minute to launch on my laptop.  I see the same behavior on my desktop, and on other systems I've demoed with.

Once it's started for the first time subsequent loads seem to be faster, but the initial launch is always slow.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
