### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by pyalot** [toji/chrome-webvr-issues#11]
When walking or moving the head, some stuttering (as in dropped frames maybe) is visible. I don't know where this comes from (could be GC related) but it should be investigated.

**Comment by hh3m** [comment]
Any progress on the Latency part? I think you guys (MozVR and ChromiumVR teams) should focus on getting the Latency for WebVR to a more acceptable level (comparable to native apps).

I don't intend to be the 'smart guy', but I think that's the most important thing to fix for now.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
