### ISSUE TITLE
Reloads lead to Aw, Snap ran out of memory

### ISSUE THREAD

**Issue by Prof-Abbott** [toji/chrome-webvr-issues#113]
When debugging I often have to reload (F5 or the Reload this page symbol) the page after a code change. The Oct 29 version after a few reloads (happens with any of my apps, it's not specific to just one) I get Aw, Snap, Chromium ran out of memory while trying to display this web page.

My system memory increases with each re-load but never to more than 50%.

I also get the impression (harder to get evidence) that the VR is slowing down with each reload.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
