### ISSUE TITLE
WebVR Tracking Issue?

### ISSUE THREAD

**Issue by mrLoganite** [toji/chrome-webvr-issues#114]
Hi,
While doing some testing I noticed that WebVR apps in chrome don't seem to track as well as other apps and it doesn't appear to be performance related.

Steps to reproduce the issue:
Run any WebVR app in Chrome and bring up the Steam overlay. Examine the greyed out background app around the edges of the steam overlay. You will notice that it bounces around ever so slightly. 

No bring up a native app like "Destinations" and then bring up the overlay. You can see clearly that the background app is "rock solid" with the edges of the overlay.

This ever so slight bouncing around of the headset view is probably destroying quite a lot of the "immersion" factor and probably causing a section of the community discomfort.

Now it might be that native pc engines that use steam API's use some kind of "smoothing" algorithm which suppresses these slight movements but whatever it is , it makes a big difference to the quality of the VR Experience.

**Comment by capnmidnight** [comment]
I have certainly seen the issue you describe. I think this ticket covers it: https://github.com/toji/chrome-webvr-issues/issues/73

Brandon has mentioned in the WebVR slack that there are several frames of latency that WebGL images go through before leaving Chrome, and that it's a fundamental architectural limitation preventing a fix.

**Comment by mrLoganite** [comment]
Ah yes, must of missed that post.
Interestingly reports indicate the Firefox doesn't have the same issue so it looks like the Mozilla team might have solved an issue that the Chrome team have yet to solve ;)

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
