### ISSUE TITLE
Source code of Oct 29 build

### ISSUE THREAD

**Issue by huningxin** [toji/chrome-webvr-issues#116]
The [Chromium Experimental Branch](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_1) (latest commit is [42bdd7f](https://chromium.googlesource.com/experimental/chromium/src/+/42bdd7f3bc1dd61a4b49b763a96e72deeee01165) on Sep 13) seems not updated to Oct 29 build ([Release Notes](https://docs.google.com/a/intel.com/document/d/1dP9m3WLh2lsBs9jJ9LRwv1l0AtuBQAqGLAV-fUbtz2U/edit?usp=drive_web)).

Is the location of source code changed?

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
