### ISSUE TITLE
WebVR, oculus and streetview

### ISSUE THREAD

**Issue by SprinterSports** [toji/chrome-webvr-issues#117]
Hi Brandon,

Great program.  Love the potential.

How can I use it with an Oculus for streetview??
I don't mind creating my own website with street view in it. But I presume it needs to be embedded with VR code? I presume i need to achieve getting the icon with those glasses with the 'ENTER VR' on them? How do I do that?

if you could help it would be a life saver!!! I have been trying so many different ways to get the oculus to go with streetview. 
Any help would be very appreciated. Thanks.

All the best
David Miers

**Comment by SprinterSports** [comment]
Hi Brandon,

Will the google glass code that causes the VR glasses icon do the trick? Will that work for oculus via your webVR?

-David

**Comment by kzahel** [comment]
It looks like somebody had a project to do this, but is using outdated APIs and libraries.
Perhaps you could try using it as a starting point: https://github.com/troffmo5/OculusStreetView

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
