### ISSUE TITLE
[Vive] Lots of object position flickering when asynchronous reprojection is on and headset is rotated

### ISSUE THREAD

**Issue by AgentME** [toji/chrome-webvr-issues#119]
There's a lot of flickering of object's positions in all webvr demos I've tried when SteamVR has the "asynchronous reprojection" setting on. (I believe it [was only added recently](http://www.roadtovr.com/steamvr-update-adds-asynchronous-reprojection/), though it seems to be on by default now.)

I notice that if I try hard not to rotate my headset at all while moving, the flickering is minimal. I think that this issue might just be a symptom of this problem: https://github.com/toji/chrome-webvr-issues/issues/73#issuecomment-263172110. Chrome is repositioning objects as the vive rotates, putting them into different positions than where they were projected to be by vive's asynchronous reprojection. (However, I don't see this flickering issue in Firefox while I do see that other issue, so maybe they don't have the same root cause, or Firefox has worked around the flickering issue without addressing the root cause.)

**Comment by sjpt** [comment]
I noted bad flickering too: ChromeVR, Vive and more recent SteamVR.
I've found the best settings for me are

Performance/Allow asynchronous reprojection: off
Performance/Allow interleaved reprojection: off  (didn't make much difference one way or the other)
Developer/Enable Always-on reprojection: on

**Comment by sjpt** [comment]
This seems to be resolved using webgl2; but at the price that the display on the canvas is lost.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
