### ISSUE TITLE
All tabs crash in chrome build on Windows 10

### ISSUE THREAD

**Issue by discordianfish** [toji/chrome-webvr-issues#121]
Hi,

I've downloaded chrome from https://webvr.info/get-chrome/. I can start it but every tab crashes, no matter of webvr content, regular webpages or even the settings page. Will update issue if I can figure out how to get more details out of it.

**Comment by micahstubbs** [comment]
@discordianfish experience this issue too on Windows 10.

my workaround is to use the August 29th build

https://drive.google.com/drive/u/1/folders/0BzudLt22BqGRQUExYzVoLU5VT2c

**Comment by discordianfish** [comment]
@micahstubbs The weird thing: I have similar issues with firefox nightly. It works better, but sometimes animations are 'off' as well.. Unfortunately not very familiar with browser nor js internals to dig deeper on my own. If somebody has pointers, let me know.

**Comment by micahstubbs** [comment]
@discordianfish thanks for adding details. hopefully we'll see a new WebVR Chromium release with a fix for Windows 10 soon :crosses-fingers: 😅

**Comment by sjpt** [comment]
I don't think it is Windows 10 related.  We are using the 29 Oct build (riskily, in an exhibition) on Windows 10 with almost no problems.  

I do get quite a few issues when I use Developer Tools, especially after a few live code changes and page refreshes.

**Comment by denisfitz57** [comment]
The only recent version that hasn't crashed on all tabs for me has been Version 55.0.2869.0 (64-bit)
The latest (56.0.2910.0) crashes as well, 
HOWEVER, it doesn't crash if 55.0.2869.0 is running when I start it, and once it does start, I can close 55.0.2869.0 and new tabs open without a problem.
Webvr is working in both of these versions, but still no luck with either in using Oculus Touch controllers

**Comment by anlumo** [comment]
I just had the same issue. The experimental build (Feb 17) was on my desktop, but as soon as I moved it to D:\, it started to work fine.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
