### ISSUE TITLE
Missing bindings on Oculus Touch for Gamepad API

### ISSUE THREAD

**Issue by tbalouet** [toji/chrome-webvr-issues#122]
Sorry I understand this should be issued in the Gamepad API github, but couldn't find it, so I hope you don't mind me putting it here.

Working on the Oculus Touch Controllers to write an a-frame component (https://github.com/tbalouet/touch-controls), I realized there was some bindings missing in the Gamepas API:
- Oculus Button (right controller) touchstart/touchend
- Menu button (left controller) touchstart/touchend
- Grip touchstart/touchend (both controllers)
- Trigger touchstart/touchend (both controllers)

Thanks for the hard work!

**Comment by kzahel** [comment]
Also, what about capacitive touch? Is this in works for the gamepad extensions?

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
