### ISSUE TITLE
WebVR supported but no VRDisplay on Moto E

### ISSUE THREAD

**Issue by andreasplesch** [toji/chrome-webvr-issues#124]
https://webvr.info/samples/00-hello-webvr.html

The phone obviously has a display so I am at a loss. It is low end so does not have all sensors?

Polyfill works but returns wrong renderWidth.

Chromium WebVR apk 12/16 version:

The Chromium Authors
Copyright 2016 The Chromium Authors. All rights reserved.
Chromium	57.0.2947.0 (Official Build) unknown (32-bit)
Revision	71d41b68d19128f434058207eaf904b0de26f77d-refs/heads/master@{#437664}
OS	Android 5.1.0; XT1528 Build/LPIS23.29-17.5-2
JavaScript	V8 5.7.201
User Agent	Mozilla/5.0 (Linux; Android 5.1; XT1528 Build/LPIS23.29-17.5-2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2947.0 Mobile Safari/537.36
Command Line	--use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --use-mobile-user-agent --enable-pinch --enable-viewport --enable-overlay-scrollbar --validate-input-event-stream --disable-gpu-process-crash-limit --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --ui-prioritize-in-gpu-process --profiler-timing=0 --prerender-from-omnibox=enabled --enable-dom-distiller --flag-switches-begin --enable-webvr --enable-features=GamepadExtensions --flag-switches-end
Executable Path	No such file or directory
Profile Path	/data/data/org.chromium.chrome/app_chrome/Default
Variations	12af154-7e0bd872
853359fa-f7de5af1
90757ebb-3f4a17df
241fff6c-ca7d8d80
1e528f0f-15305a2
236d5d9e-347fc86a
e036a196-3f4a17df
77207729-3f4a17df
4bf94d2-262f996f
2a33b90e-3f4a17df
ba3f87da-92cc81ec
3982a4f-3f4a17df
f3499283-2c7b8482
63d6a31a-3f4a17df
3fbe5359-3f4a17df
5e3a236d-4113a79e
6ce7d7b5-3f4a17df
a5e07222-1582e5f6
3e1c19dd-3f4a17df
9773d3bd-3f4a17df
93731dca-3f4a17df
2e109477-e2e291f1
64cbdfc2-3f4a17df
6b121ae7-3f4a17df
5139837c-3f4a17df
7f8176d9-3f4a17df
b7786474-d93a0620
23a898eb-e0e2610f
158a87f-3f4a17df
7382e39a-3f4a17df
9e46b3e5-3f4a17df
868bda90-3f4a17df
2182dcae-69de46be
4ea303a6-3f4a17df
ce152c12-3f4a17df
3a007b7-3f4a17df
826d6cab-96e3ef3c
8b4d89aa-3f4a17df
64224f74-fbb2b036
ca314179-ea08a3f2
c5073fab-3f4a17df
867c4c68-3f4a17df
7fc902e8-3f4a17df
db5efd10-88e62167
d747916f-d747916f
477f6800-72c07fe0
dd139bd7-3f4a17df
fe05be5f-4ad60575
36e71e36-3f4a17df
828a5926-d8f52f32

**Comment by andreasplesch** [comment]
https://github.com/googlevr/webvr-polyfill/pull/180 seems to address this situation with ALWAYS_APPEND_POLYFILL_DISPLAY . It looks like the recommendation would be to essentially always use the polyfill to cover cases such as above, even if the expectation is that a browser with native webvr is available ?
Also, it looks like the native webvr in chrome does not return a vrdisplay if mobile devices only have a tilt sensor but no rotation around Y (yaw, gamma) sensor ? This would be quite opinionated. Why not let the API consumer (app) decide what to do in this case ? After all, the polyfill is fine with this.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
