### ISSUE TITLE
requestAnimationFrame passes wrong timeStamp in latest Chromium build

### ISSUE THREAD

**Issue by customlogic** [toji/chrome-webvr-issues#126]
The VR display's "requestAnimationFrame" function should pass a parameter to the callback that represents the current time ([docs](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)). However, in the latest Chromium ( Oct 29 build) with an HTC Vive i'm seeing a bogus time being sent. The time starts at -92 seconds and counts up to 0 then continues on as normal. This problem didn't exist in previous builds (Sept 23, etc).

I've created a quick example to show what's going on:
https://jsfiddle.net/zs4j5s3j/4/

If you open this in regular chrome, or previous builds, you'll see the current time reported correctly. In the Oct 29 build, you'll see the negative time I'm talking about:
![chromium_bug](https://cloud.githubusercontent.com/assets/1166244/21700101/76eca3e4-d353-11e6-9fb2-a75027657bcd.png)

**Comment by machenmusik** [comment]
Actually, I believe this is resolved in the early Feb 2017 build...

**Comment by Sebkasanzew** [comment]
I can confirm that the time in the example ([https://jsfiddle.net/zs4j5s3j/4/](https://jsfiddle.net/zs4j5s3j/4/)) is positive again in the Chrome Feb 17th build.

**Comment by customlogic** [comment]
I checked as well, and it does appear to be fixed. Thank you!
