### ISSUE TITLE
I can not get WebVR to load on my HTC Vive

### ISSUE THREAD

**Issue by acarden84** [toji/chrome-webvr-issues#128]
I have used both Cromium and Nightly and and followed all the instructions to set up both browsers but I can not get eater to launch WebVR content to my HTC Vive. I have windows 10 installed and it is up to date. What could I be missing ?? My personal e-mail is anthonycarden84@gmail.com

**Comment by dangodev** [comment]
@acarden84 Chromium has some issues; Nightly is working fine with Vive. For Nightly, [read the instructions carefully](https://github.com/Web-VR/iswebvrready/wiki/Instructions%3A-Firefox-Nightly-for-HTC-Vive-on-Windows). If you have already, try repeating every step again, carefully. Chromium will be back up once the community figures it out (seems to be related to a [gamepad issue](https://github.com/toji/chrome-webvr-issues/issues/135#issuecomment-276939466)).

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
