### ISSUE TITLE
zero'd position not persisting after page refresh.

### ISSUE THREAD

**Issue by caseyyee** [toji/chrome-webvr-issues#13]
In this example:

http://caseyyee.github.io/three.js/examples/webgl_effects_vrposition.html

When zero'ing the sensor by running:

vrControls.zeroSensor()

The position resets/zero's properly.

Upon refreshing the page, the position needs to be reset again.   The zero'd position should be persisted even after refresh.   In Firefox VR builds, the reset position is persisted until the browser session is closed.

Why this is important:
When moving user between web VR pages, the user shouldn't have to reset the position for every page that is loaded.  

edit:  additional details
using:
Chromium Version 40.0.2199.0
Mac OSX 10.10 (14A389)
Oculus rift DK2 with firmware 2.12
Oculus runtime 0.4.3

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
