### ISSUE TITLE
Chrome gets killed by SteamVR

### ISSUE THREAD

**Issue by andresiraola** [toji/chrome-webvr-issues#132]
If you close the SteamVR status window, chrome gets killed :(

By status window I mean this one:

![image](https://cloud.githubusercontent.com/assets/11182419/22270559/ebd73cd0-e26e-11e6-94bd-e0fc34361ff0.png)

**Comment by stevel4857** [comment]
Same here. Without Steam neither Chrome nor Nightly would work. It somehow bypasses Oculus trying to keep it from functioning (my guess)

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
