### ISSUE TITLE
Camera pose(orientation) get reset f i go out of VR mode in Oculus.

### ISSUE THREAD

**Issue by swomack** [toji/chrome-webvr-issues#133]
This issue can be reproduced using the following sample - 

https://webvr.info/samples/03-vr-presentation.html

To reproduce - 

1) Click on "Enter VR".
2) Rotate your head around.
3) Keep your head still and click on "Exit VR".
4) Keep your head still and click on "Enter VR" and see that the camera orientation has been reset.

**Comment by toji** [comment]
This is a known issue cause by an unfortunate synchronization hack. Definitely on my TODO list to fix, but I don't have a timeframe to give for when I'll be able to address it.
