### ISSUE TITLE
Android Chromium: three.js shadow maps cause render issues

### ISSUE THREAD

**Issue by customlogic** [toji/chrome-webvr-issues#134]
In the current Android Chromium build (ChromePublic-webvr-native-WIP-20161215a.apk), scenes that use shadow maps cause broken/flashing rendering in the right eye.

An example: https://threejs.org/examples/?q=webvr#webvr_shadow

![screenshot_20170126-120609](https://cloud.githubusercontent.com/assets/1166244/22348310/142735e4-e3c0-11e6-9c2b-85960345427b.png)

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
