### ISSUE TITLE
Rift Touch analogue triggers shown as 'touched' when at rest 

### ISSUE THREAD

**Issue by yaustar** [toji/chrome-webvr-issues#137]
Version: Chromium 56.0.2910.0 (64-bit)
OS: Windows 10

When the controller is at rest, the buttons for the analogue grip and trigger are shown as 'touched'.

![image](https://cloud.githubusercontent.com/assets/16639049/22603939/3d90d804-ea41-11e6-8012-181469bdef8f.png)

**Comment by toji** [comment]
Define "at rest". You mean when the controller is not being held in your hand at all? Or when the controller is being held but no buttons are being pressed?

**Comment by sjpt** [comment]
We have had that issue with some controllers; more on the trigger than the gamepad.  As suggested by someone in another thread, Irritating, we worked around it with some slightly more forgiving code.  Basically a hardware error on the Vive that they could work around in the firmware.    

More irritating to us has been the click on the touchpad.  If you click near the edges it doesn't register a touch at all, and even when you can clearly feel the click of the pad going down, it still registers no touch/no click.  The sculpting at the bottom of the pad really encourages clicking in this way.

**Comment by yaustar** [comment]
@toji At rest being on the desk with no buttons pressed.

**Comment by BKcore** [comment]
I've fiddled with this a bit recently on the Touch controllers, and from what I can tell both triggers and grips detect the first "touch" but do not revert back to `touched: false` after moving your finger away. It does work fine for X/Y and A/B buttons though.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
