### ISSUE TITLE
getFrameData returns false when called from within a window.requestAnimationFrame callback

### ISSUE THREAD

**Issue by hubatish** [toji/chrome-webvr-issues#138]
getFrameData recently started returning false when I call it from within a window.requestAnimationFrame callback. I'm not presenting, so it seems like both window's and VRDisplay's requestAnimationFrame should do the same thing. This isn't necessarily something that should be fixed, but clarification would be nice. My use-case is magic window mode and I'm just trying to get the nice orientation from WebVR.

Related to these two (unresolved) discussions on the spec:
[When is getFrameData/getPose allowed to query new values when not presenting?](https://github.com/w3c/webvr/issues/81)
[Clarify what happens when submitFrame is called at the wrong time](https://github.com/w3c/webvr/issues/138)

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
