### ISSUE TITLE
Fullscreen permission prompt is not accessible on VR headset

### ISSUE THREAD

**Issue by caseyyee** [toji/chrome-webvr-issues#14]
When requesting full-screen with pointer lock, the door-hanger permission UI  is impossible to see and interact with as its entirely out of view on the VR display.   

The solution might be simply to have the permission ui to show up on the users main display instead.

The workaround for the issue is to first request full-screen and pointer lock without specifying vrDisplay options.  This presents the permission on the users main display first.  Once the permission is granted, you can then re-request full-screen with vrDisplay options.

Pointer lock is important to have when requesting full-screen since the native OS cursor is not at all useable for VR use.  Any mouse-based cursor replacement would probably need to use pointerlock to work properly.

**Comment by toji** [comment]
The issue of accessing general UA in the headset is still outstanding, but the new API eliminates the need to interact with the fullscreen prompt and allows for basic interaction to happen on the external monitor now. Closing.
