### ISSUE TITLE
Pressing Vive controller button causes chrome.exe unresponsive

### ISSUE THREAD

**Issue by huningxin** [toji/chrome-webvr-issues#141]
I am using the Feb 17 build with HTC Vive.

The controller can be tracked correctly in the controller sample (https://webvr.info/samples/XX-vr-controllers.html).

However, if I press the button of the controller, the SteamVR shows "(unresponsive) chrome.exe".

Any thoughts?

**Comment by sjpt** [comment]
Looking OK to me: 17 Feb Chrome + 31 Jan SteamVR.  The controllers don't seem to do anything other than vibrate when I press any button (not sure if they are meant to), but no crash.  

To narrow down the issue: how does it behave with 
https://threejs.org/examples/?q=webvr#webvr_vive_dragging

**Comment by huningxin** [comment]
I am using 17 Feb Chrome + 31 Jan SteamVR as well. No crash, but system UI in HMD and 
"(unresponsive) chrome.exe" in the SteamVR status.

Attaching the screenshot:
![image](https://cloud.githubusercontent.com/assets/1005673/23345499/44670ba8-fcca-11e6-9276-e9b18bd4f189.png)


> To narrow down the issue: how does it behave with
> https://threejs.org/examples/?q=webvr#webvr_vive_dragging

No controllers detected in this sample.

**Comment by huningxin** [comment]
Fixed by enabling the gamepad extension flag.
