### ISSUE TITLE
submitFrame must be called within a VRDisplay.requestAnimationFrame callback

### ISSUE THREAD

**Issue by Noxalus** [toji/chrome-webvr-issues#142]
Hello everyone :)

I'm currently writting a C++ app that will be available in the browser thanks to Emscripten, and I would like to use WebVR in this app.

Actually, I already did this job 5 months ago, and it worked as expected, but today, the same code seems to have a different behaviour.

What I get is a loading screen with the message telling "chrome.exe is loading [...]". However, the code seems to be executed as expected, the call to `requestPresent()` is properly done (no error) when the HMD is presenting and the call to `submitFrame()` is done after rendering each frame. (the source code can be found [here](https://github.com/aerys/minko/blob/dev/plugin/vr/src/minko/vr/WebVR.cpp#L137))

I have a warning in the Chrome developer console: `submitFrame must be called within a VRDisplay.requestAnimationFrame callback.`. But in my case, the rendering is obviously be done by the C++ code, I don't want to use this `requestAnimationFrame`, and I hope that it's not why the `submitFrame` doesn't send anything to the HMD.

Do you know what happen?

Thanks in advance for your help.

**Comment by Noxalus** [comment]
A quick update to say that the same application, with the same device and computer works as expected with an older version of Chromium for WebVR ([this one](https://drive.google.com/uc?export=download&id=0BzudLt22BqGRc2lEWDg2NkptNzg) => September 23, 2016). And there is no warning in the dev console when I call `submitFrame()` without using `requestAnimationFrame()`.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
