### ISSUE TITLE
aaalmost there:  tiny VRdisplay in chrome on Moto G4 Lenovo android

### ISSUE THREAD

**Issue by coderofsalvation** [toji/chrome-webvr-issues#143]
Enabled the chromeflags in the chrome devbuild (59.0.3050.4).

it seems the api works, but the vrdisplay shows a very tiny result in the corner of the display.
Cardboard gets triggered, but suffers from the same issue:

![image](https://cloud.githubusercontent.com/assets/180068/24440632/89f22214-1455-11e7-9d5c-78184ae36f51.png)

Any ideas?

**Comment by Trixter313** [comment]
Same issue here with Chrome 60.0.3075.0 on a Nexus 6P
![screenshot_20170419-041531](https://cloud.githubusercontent.com/assets/7178055/25170026/1f7ee2a6-24b7-11e7-900c-e69eac074eb4.png)

**Comment by coderofsalvation** [comment]
Ok I have 2 theories as it seems to work now on my phone:

* when i rotate the phone back and forth, suddenly it displays correctly
* i also used another Google cardboard QR code, but im not sure whether that helped or not

interesting..

**Comment by randytayler** [comment]
Same problem. Chrome 58.0.3something, Android 6.0.1, Samsung Galaxy 7.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
