### ISSUE TITLE
https://mozvr.com/puzzle-rain and http://h3.hypernom.com/ do not work in Vive

### ISSUE THREAD

**Issue by markbradley1982** [toji/chrome-webvr-issues#144]
Hello,

I am using the Feb 17th build of Chromium. Chromium + my Vive works (though there is some wobbling which is a separate open and unresolved issue) with A Painter, A Blast, City Builder, etc but it doesn't work on the following:
 
http://h3.hypernom.com/

With this particular site, my headset tracks but nothing is output to the headset's display. The only output I get is to my PC monitor with side by side mode. 
 
https://mozvr.com/puzzle-rain

Nothing seems to work. After I click Enter VR I see some stuff in the browser but that's it. There's no tracking of my headset and nothing is output to the headset's display.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
