### ISSUE TITLE
Latest NVidia drivers cause Chromium to crash on WebVR present

### ISSUE THREAD

**Issue by customlogic** [toji/chrome-webvr-issues#147]
**[TL;DR: If Chromium is suddenly crashing when you try to "Enter VR", the problem is the latest NVIDIA drivers. Install older ones, and Chromium will work again]**

I've been experiencing crashes with the Feb17 Chromium build on machines that have been working fine before. I suspected a SteamVR update might have broken things again, but it turns out the cause is updated NVidia drivers. Reinstalling older drivers (376.33) makes things work normally again.

The crash happens like this:
- Open a webVR site in Chromium (such as the [WebVR Presentation Sample](https://webvr.info/samples/03-vr-presentation.html))
- The VR device is detected just fine, and headset tracking and control tracking is working fine
- Press the "Enter VR" button
- The window goes black, closes, re-opens with black and grey boxes, closes again, then reopens with an "Ah snap" error message

![ezgif-1-2e5995ff12](https://cloud.githubusercontent.com/assets/1166244/25539141/9d217242-2bfa-11e7-9af1-18425d37165c.gif)

I've seen this problem on at least 4 computers, all Windows 10. An auto-update installed new NVidia drivers, and this was the start of the problem. After tracking down the cause, I ran an experiment to confirm that the drivers are causing the problem.

Our Falcon NW tower (Windows 10, GTX 1080) was working fine with the 376.53 drivers. I manually installed the latest driver (381.89). Then, without rebooting or changing anything else, I tried Chromium WebVR and experienced the crash. Then I installed an older version of the drivers(376.33), again no other changes or reboot, and Chromium WebVR is working fine.

**Comment by martijns** [comment]
Confirming the same issue. Narrowed it down to driver version 381.65 introducing the problem (released on april 6th). Driver version 378.92 (released on march 20th) works.

**Comment by mflux** [comment]
Having this same issue as well. 382.05 May 4, 2017 Nvidia driver update

**Comment by cfanguy** [comment]
Can also confirm that 378.92 works in Chromium while 382.05 does not.

**Comment by godlzr** [comment]
Had the same issue with 382.53, resolved by reinstalling 387.92

**Comment by sjpt** [comment]
I am pleased to say that 384.94 seems to work fine for me.

I am still using the 56.0.2902.0 version of ChromeVR because of the timebomb on the later versions,
but  the 56.0.2910.0 version does seem to work with the new driver.

(by the way, I think godlzr meant 378.92 above)

**Comment by Joshua-Smith** [comment]
Same happy result as sjpt, using Brandon's latest build. This issue can probably be closed now.

**Comment by customlogic** [comment]
It's true! The 384.94 update fixes the issue, and Chromium from Jun 6 is running fine for me now
