### ISSUE TITLE
All attempts w/ htc-vive failing (Windows 10, Alienware L7)

### ISSUE THREAD

**Issue by danbri** [toji/chrome-webvr-issues#149]
I've tried a number of combinations without any success. Fairly fresh Windows 10 laptop with latest SteamVR (sometimes trying SteamVR beta channel). Have launched browser with right-click "run with graphics processor" of Integrated graphics (default)" and "high performance (nvidia)". Also tried for Firefox Nightly with no success. The most common result (testing with https://threejs.org/examples/?q=webvr#webvr_cubes or the https://aframe.io/examples/showcase/helloworld/) was for the 3d scene to display in the desktop browser, for it to be responsive to the headset's movements, but for 'enter vr' to cause the desktop SteamVR to show "(unresponsive)chrome.exe" and nothing change within the headset. 

My setup seems reasonably functional otherwise, plenty of Steam-purchased VR apps work (although a few do fail e.g. google earth hangs), webgl generally works etc.

Most recent variation tried: https://gist.github.com/anonymous/3e3d4d93ed7addd00495938c7ccfa5b7 (steamvr system report), with chromium_webvr_v1.1.win.zip from https://webvr.info/get-chrome/

**Comment by sjpt** [comment]
Try Nvidia driver 378.92 or earlier.   There are issues with ChromeVR and
later versions.
I don't think that explains issues with Firefox as well, though.

**Comment by danbri** [comment]
Installed Nvidia 378.92,

> SteamVR Version 2017-05-11 (1494535542)
Steam:	Public (beta)
Tracking:	lighthouse
OS:	Windows 10 (10.0.0.14393)
Direct Mode Graphics:	NVIDIA (378.92)

System
Admin:	No
Async Reprojection:	Enabled
Allow Reprojection:	Yes (Good)
Force Reprojection:	No (Good)
Performance drops:	5/1 0/2 0/3 0/4 5/7852
User IPD (m):	0.069
Displays - Direct Mode
Display 0: \\.\DISPLAY1 1920x1080 @ (0, 0) Intel(R) HD Graphics 530 Primary 
Monitor 0: \\.\DISPLAY1\Monitor0 Generic PnP Monitor
Display 1: NvAPI 2160x1200 @ (0, 0) NVIDIA  Direct Mode

I see same behaviour in chromium_webvr_v1.1_win/Chrome-bin/chrome.exe using SteamVR[beta]

**Comment by phtaylor** [comment]
just checking, but make sure you restart after installing. I did have the same issue but the older drivers fixed it.

**Comment by phtaylor** [comment]
and also, I think after the windows update you may need to re-enable webvr in about://flags.

**Comment by danbri** [comment]
I have it running. I believe it was two problems, the first self-inflicted:

1. I was not careful enough when testing and I think a lot of times I was running with the weaker integrated GPU, which seems to handle basic webgl but not webvr for vive.
2. I had missed that webgl was not available when the Chrome WebVR build was actually running. I fixed that with chrome://flags#ignore-gpu-blacklist and we're off. 

I guess I should re-upgrade my Nvidia drivers and flip back to SteamVR[beta], but first I have to try a few more WebVR demos :) I'll close the issue but report back if I figure out any combinations are breaking.

**Comment by danbri** [comment]
@phtaylor I didn't re-enable webvr as such (it was enabled but not working) but that was along the right lines:)
