### ISSUE TITLE
Build will expire soon (Desktop)

### ISSUE THREAD

**Issue by modulesio** [toji/chrome-webvr-issues#151]
The build up on https://webvr.info/get-chrome/ is soon expiring.

> Yes, this puts the onus on me to have new builds at least every 3 months or so. Or, you know, better yet we could just get it in top-of-tree chrome..

Will this onus continue to be met :P? If not, then perhaps it'll be time to update https://webvr.info/ to say Chrome/Chromium does not support WebVR experimentation anymore.

**Comment by Joshua-Smith** [comment]
I was at AWE last week, and saw dozens of companies that are relying on this experimental build to demonstrate their developing capabilities. If a new build doesn't happen, this is going to be a severe blow to the growing WebVR developer ecosystem.

**Comment by Joshua-Smith** [comment]
Brandon did a new build on June 6. Crisis averted!

**Comment by toji** [comment]
Yup, sorry for the scare. Only reason it took so long is I was hoping to not need the experiemental build at all and just get something out in Canary. Not quite there yet, sadly!

**Comment by modulesio** [comment]
Figured. Thanks for this in the meantime @toji!
