### ISSUE TITLE
Gamepad "Oculus touch (Left)" and "Oculus touch (Right)" is found when Xbox gmaepad is connected.

### ISSUE THREAD

**Issue by swomack** [toji/chrome-webvr-issues#153]
I have been using Xbox gamepad with Oculus. In the latest build (and previous build as well) I am getting "Oculus touch (left)" and "Oculus touch (right)" in the `navigator.gamepads` if i connect my Xbox controller.

Is this intentional?

I am using three.js and they have updated their code in `ViveController.js` in which they have added the following check - 

`if ( gamepad && ( gamepad.id === 'OpenVR Gamepad' || gamepad.id === 'Oculus Touch (Left)' || gamepad.id === 'Oculus Touch (Right)' ) )`

instead of - 

`if ( gamepad && gamepad.id === 'OpenVR Gamepad' )`

So whats happening is that, when i connect my Xbox controller, a vive controller object is showing up. 

This problem is reproducible for all of Three.js VR examples.

If this behavior is intentional, i will post bug to three.js so that they can update their code.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
