### ISSUE TITLE
sittingToStandingTransform incorrect if Vive is not tracking when vrDisplay is first established

### ISSUE THREAD

**Issue by mflux** [toji/chrome-webvr-issues#154]
To reproduce:

1. Close ALL Steam VR processes in Task Manager (VR Compositer, VR Dashboard, VR Server, and Steam Tours if it's open)
2. Close Chromium
3. **Cover up entirely your Vive headset so it does not track**
4. Open Chromium and enter WebVR

You should see this as the standing matrix:

![screenshot 2017-07-20 15 13 44](https://user-images.githubusercontent.com/1041360/28441283-de12d476-6d5e-11e7-9f13-2213aeeb6d82.png)

That's an identity matrix. It will stay this way as long as you're still in VR and will only fix itself if you restart your WebVR instance (refresh the page and go back into VR, restart Chromium, etc).

It SHOULD look like this:

![screenshot 2017-07-20 15 14 25](https://user-images.githubusercontent.com/1041360/28441296-e86fcec4-6d5e-11e7-8992-3eb482572c63.png)

**Comment by mflux** [comment]
On Firefox Nightly the same behavior happens except that if it starts tracking again the position is corrected.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
