### ISSUE TITLE
Oculus works fine outside Chrome but no WebVR inside Chrome

### ISSUE THREAD

**Issue by greggman** [toji/chrome-webvr-issues#157]
Enabled webvr in about:flags.  If I put the oculus on my head the oculus software starts and I see the oculus hub/store whatever it's called. Going to any WebVR demo says no support or no display found

How do I troubleshoot?

There isn't much info around the web. The only actionable thing I found was to go into the nvidia control panel and tell it to use nvidia for Chrome. about:gpu verifies chrome is using the nvidia gpu not the integrated gpu. So does webglreport.com

Also yes, unknown sources is enabled in the oculus settings. That's also verified since I can run SteamVR stuff which required that.

Any other ideas?

**Comment by sjpt** [comment]
Are you using a standard Chrome build?

Current standard Chrome confusingly has a flag for WebVR but no support for
it.
Either try 64 bit Firefox, which has WebVR built in, or the special build
of Chrome for VR at https://webvr.info/get-chrome/
