### ISSUE TITLE
Black present screen with mipmap filtering on loaded textures

### ISSUE THREAD

**Issue by AntoineConffx** [toji/chrome-webvr-issues#159]
If I enable any kind of mipmap filtering on a 2d texture then the VR screen becomes black. The same code works (kinda) in nightly so i can only assume it's an issue with the chromium build.  I am currently using webgl 2.0 and a gtx 980 with latest nvidia drivers

**Comment by AntoineConffx** [comment]
It's actually related to binding a texture sampler. 
If I don't bind a texture sampler then mipmapped textures work fine.
If I bind a texture sampler with mipmapped filtering then I get a black screen in Oculus.
If I bind a texture sampler with non mipmapped filtering it works fine.

**Comment by AntoineConffx** [comment]
Temporary workaround is to unbind the bound sampler object before presenting to the headset. I am assuming the webvr compositor is not unbinding the sampler states before distorting the canvas

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
