### ISSUE TITLE
Chrome Webvr w/ daydream crashes in Samsung  S8 because resolution settings

### ISSUE THREAD

**Issue by fevr360** [toji/chrome-webvr-issues#160]
I found that if you don't change the display resolution setting to WQHD+ in S8+(which default value is FHD+, see https://www.cnet.com/how-to/samsung-galaxy-s8-settings-to-change-right-away/), webvr cannot turn on. Webvr button clicked, goes to black screen, then goes back to normal non-vr display, and chrome crashes. Maybe related to (https://bugs.chromium.org/p/chromium/issues/detail?id=776907&q=component%3ABlink%3EWebVR&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by tbalouet** [comment]
Experienced it as well on S8, thanks, I would have had to search for a while but your issue was the first one to pop up by looking "chrome webvr crash" in Google.
Gear VR automatically set the max resolution on S8 when going into the headset, so maybe that'd be to the Daydream SDK to handle this instead of the browser though.

**Comment by danrossi** [comment]
Confirming this an issue. Trying to launch Chrome automatically to Daydream view in S8 it crashes back to home screen. 

If I enable webvr flags and launch to webvr display which is now Daydream view if installed. It will also do the same. 

The controller was working and now won't operate either. 

S8 just got an October security level patch. So maybe it needs another update ?

**Comment by danrossi** [comment]
My issue is different. I am on S8. not S8+. The display is already WQHD+. Daydream fails to launch Chrome. Goes back to home screen.

**Comment by danrossi** [comment]
Daydream on S8 totally not ready yet.

**Comment by danrossi** [comment]
When I am in battery saving mode it uses a lower resolution. Gear VR notifies to disable it.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*

**Comment by danrossi** [comment]
So where to report Daydream view launching not working on S8 ? It crashes as reported. 

Thanks for the update. So when will the flags not be needed ?

Samsung Internet in Gear VR has a menu to toggle webvr but doesn't accept origin trial.

**Comment by danrossi** [comment]
Confirming webvr flag enabled in Canary. When will it move to production without flag requirements ?  Webvr flag is also in Chrome too.
