### ISSUE TITLE
My demo is crashing ChromeVR but not FirefoxVR

### ISSUE THREAD

**Issue by craigsketchley** [toji/chrome-webvr-issues#18]
Hey guys,

I'm currently working on a WebVR plugin for [Cesium](http://cesiumjs.org), a WebGL virtual globe engine, and would like to get it working in Chrome.

My [cesium-vr demo](http://nicta.github.io/cesium-vr/) works fine in Firefox but crashes when I go fullscreen in the current Chrome builds (OSX or Windows). I'm using the 0.4.4 oculus runtime. I grabbed the [stack trace](https://gist.github.com/craigsketchley/e7870f077eba4309845f) I'm getting in OSX (I'm not sure how to get that in Windows).

Here's [my repo](https://github.com/NICTA/cesium-vr) for the demo if you were interested.

Has anyone else experienced something similar with their content?

**Comment by toji** [comment]
Enough has changed since this was filed (multiple new builds, new API) that I'm gonna just consider this closed. Please file any issues you have with the newer builds, though!
