### ISSUE TITLE
Misbehavior when entering fullscreen vr mode after user is already in fullscreen mode.

### ISSUE THREAD

**Issue by toji** [toji/chrome-webvr-issues#19]
Repro steps (chrome, haven't tried in FF yet):
1. Go to mozvr.com
2. Hit F11 to enter fullscreen mode
3. Hit f to enter vr mode

Observed behavior:
Canvas contents are displayed on regular monitor instead of the HMD. Browser UI is visible, but can't be interacted with. Can't exit fullscreen.

As a workaround, I'm just going to prevent entering vr mode when the user is already in fullscreen. I tried exiting fullscreen first, but didn't get that to work for some reason.

Thanks for reading, & happy New Year! :)

Rye

**Comment by wrr** [comment]
> I tried exiting fullscreen first, but didn't get that to work for some reason.

Chrome doesn't seem to allow to exit fullscreen with Javascript API, if it wasn't entered with Javascript API but F11.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
