### ISSUE TITLE
Broken image when sensor getState not called.

### ISSUE THREAD

**Issue by wrr** [toji/chrome-webvr-issues#20]
If sensor `getState()` is not called in the render loop , a rectangle is drawn on top of the right eye view (see the screenshot). This can be reproduced with http://media.tojicode.com/webvr-test/ by removing `updateVRDevice()` call from the render loop (tested on Linux and Windows).

![webvr-bug](https://cloud.githubusercontent.com/assets/1032408/5741078/32bfed62-9c09-11e4-9cc5-5bc87ba69469.png)

**Comment by toji** [comment]
Ah, interesting. I know what that is and how to fix it. Thanks for catching the bug!

**Comment by toji** [comment]
Issue doesn't apply to newer builds. Closing.
