### ISSUE TITLE
Cardboard bug - vertically squeezed fullscreen mode.

### ISSUE THREAD

**Issue by krpano** [toji/chrome-webvr-issues#23]
The cardboard fullscreen rendering output is vertically squeezed.

Here a screenshot comparison - a panoramic image (looking down at the floor) once displayed with the Cardboard Photosphere viewer and once via WebVR in the Android Chrome Shell browser:
![webvr_vertical_scaling_bug](https://cloud.githubusercontent.com/assets/5989766/5834836/db6edb78-a161-11e4-95e2-de8726245eb7.jpg)

The reason might be the top Android bar...
Either the fullscreen mode should cover it too (like in the normal Chrome browser in fullscreen mode) or the rendering output window be scaled to the real screen height and then cropped at top by that bar height...

Best regards,
Klaus

**Comment by krpano** [comment]
The bug is still there in the new ChromeShell_Cardboard_SDK_0.5.2.apk.

Additionally the fullscreen mode is broken now (also without WebVR) - the page size/scaling in landscape mode is wrong when first starting the fullscreen mode in portrait mode and then rotating to landscape.

**Comment by toji** [comment]
Yeah, this is a particularly nasty one to work around in ChromeShell.apk because it doesn't have the same fullscreen hooks as Chrome proper does. I think the easiest "fix" for this is going to simply be getting WebVR into Chrome behind a flag and stop requiring the experimental Android build. That's in-progress.

I'll still look into this in ChromeShell and see if there's any easy fixes.

**Comment by krpano** [comment]
Yes, having WebVR behind a flag in a normal Chrome release would be the better solution, but the current ChromeShell version is basically unusable this way. Even the previous release was better.

I've made a quick video to demonstrate the bugs:
https://www.youtube.com/embed/TQ142WkP1Nc?hd=1&vq=hd1080

Here the link for testing:
http://krpano.com/plugins/webvr/test1

The bugs:

1. The fullscreen window size will be wrong (not related to WebVR) and HTML elements outside that window will be not shown.

2. When entering the fullscreen mode in portrait-mode and than rotating to landscape, then the page scaling becomes wrong. When starting in landscape and rotating to portrait the scaling will be okay but the window size will be even more wrong.

3. When entering the fullscreen mode with vrDistortion:true - the distortion will not be applied the first time. When exiting the fullscreen mode and entering it again, it will work.

I hope there can be some easy fixes...

Thanks,
Klaus

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
