### ISSUE TITLE
Direct Mode: no image in the headset

### ISSUE THREAD

**Issue by Colmea** [toji/chrome-webvr-issues#24]
Hi,

First, thank you so much for this chrome build and your work: that's awesome.
I saw that last chrome webvr build should support Direct mode with Oculus Rift, but I can't make it work.

Actually, headset movements are properly fetched by the web app (I tried de mozvr.com app, and my own three.js app), but there isn't anything on the headset screen (it's not even running).

Everything is ok with the extended mode (well, it's really annoying to move the window each time, but it works :) ).

I hope you can help me (and sorry for my english).

My config:
- Window 8.1, 64bits
- Nvidia GTX 850M
- Oculus DK2 (0.4.4)

Thanks !

**Comment by Colmea** [comment]
Ok, got it.
I have a laptop with two GC.

Oculus is running on my Nvidia gc, while the chromium browser is running on the integrated gc.
If I force chromium to run on the Nvidia graphic card, it's working.

Maybe we can force chromium on the graphic card where Oculus is running ? Or is there a way to switch graphic card when chromium is already running and user asks for VR mode ?

Thanks for your help.

**Comment by toji** [comment]
Forcing a switch on Optimus chipsets is a non-trivial subject that we've
had trouble with long before VR came along. Screws with normal WebGL too.
It's definitely something we'd like to handle better.

**Comment by tbalouet** [comment]
Hi,

Thanks a lot for the good work on the chromium build! 

It's just that I can't make the direct mode work on my oculus 2 either, I checked the GC configuration on NVIDIA and eveything is on the high performance one.

Is there an experience which is supposed to work each time and that I can try ? Are there some leads on this kind of problem that I could follow ?

I've tried using this boilerplate https://github.com/borismus/webvr-boilerplate  for my program and tried the experiments in it, motion tracking and extended mode works fine, but nothing displayed on the rift in direct mode.

My configuration : 
 - Windows 8.1 64 bits
 - Oculus runtime 0.6.0.1
 - Chromium Version 44.0.2383.0
 - Oculus DK2

Thank you very much!

**Comment by toji** [comment]
This code path has changed dramatically with the latest 0.8.0.0 SDK builds, and should work much better. (Assuming that the latest Oculus runtime works on your system, that is.)

**Comment by tbalouet** [comment]
Yes, that last part is actually the newer problem sadly. Hope Nvidia will
do some updates so it can works on Geforce GTX 870M

2015-10-25 20:16 GMT+01:00 Brandon Jones <notifications@github.com>:

> This code path has changed dramatically with the latest 0.8.0.0 SDK
> builds, and should work much better. (Assuming that the latest Oculus
> runtime works on your system, that is.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toji/chrome-webvr-issues/issues/24#issuecomment-150960021>
> .
>



-- 
<http://www.beloola.com>
*Thomas BALOUET  <http://beloola.com/balou>
<http://www.twitter.com/thomasbalou>**
<https://fr.linkedin.com/in/thomasbalouet>*
*VR CREATIVE ENGINEER @Beloola*
*Tel :* +33 (0)651-886-140

**Comment by ruofeidu** [comment]
Hi toji, I am working with the latest Chromium builds on a Dell Precision M4800 Mobile Workstation with both Intel GPU and Nvidia GPU. The Oculus demos work fine with 0.8 runtime but the latest Chromium builds show no image in the Oculus Rift. I need to use a laptop for demo. Thanks for any suggestions!
