### ISSUE TITLE
Bug - changing vrDistortion in a second requestFullscreen call doesn't work.

### ISSUE THREAD

**Issue by krpano** [toji/chrome-webvr-issues#25]
Hi,

when having requested the fullscreen mode once with vrDistortion=true or false, then any following requestFullscreen calls (after exiting the current fullscreen mode of course) will ignore the vrDistortion parameter.

Best regards,
Klaus

**Comment by krpano** [comment]
An additional request - it would be great if it would be possible to enable/disable the vrDistortion dynamically without switching the fullscreen on/off (only on Android).

I want to allow the user to switch between the Cardboard API distortion and a custom implemented distortion at runtime. That would be required when using VR headsets with a distortion different to Cardboard.

Thanks and best regards,
Klaus

**Comment by toji** [comment]
First comment is definitely a bug, but I'm not sure how to address the second. Toggling that on and off would only be applicable while the app is fullscreen, making any API to do so a bit awkward. I'll think about it.

**Comment by krpano** [comment]
Hi,

what about a simple 'get / set' API to change capabilities?

This way it should be possible to provide an easy-to-use, vendor and device/system independent and future-proofed interface.

E.g. some like this:

> var caps = vrHMD.getSupportedCaps();

First get here with an string array (or object) with the supported capabilities. The names of these capabilities could be fully individual and depending on the system/browser and the connected headset. 

As continuing the example - in the case there would be a capability named 'vrDistortion' in that array, then it could be used that way:

> var distortion = vrHMD.getCap("vrDistortion");
> ...

The getCap() function could return the current value of that capability (could be a String, Number, Boolean or undefined if that capability would be not supported).

And setting/changing that capability could be simply done by a setCap() function:

> vrHMD.setCap("vrDistortion", true);


This way it would be possible to have just one simple and stable API.
The supported capabilities itself could change from version to version and system to system.

Additionally such API could be used to provide also access to other interesting capabilities and features. It would be great to have also access these capabilities from the Oculus Rift Desktop SDK (only on Desktop):

ovrHmdCap_Present, ovrHmdCap_LowPersistence, ovrHmdCap_NoVSync, vrDistortionCap_TimeWarp, ovrDistortionCap_Vignette

The internal technical implementation of such could be made like in the OculusWorldDemo.cpp example - there a simple integer variable with several bit-flags for the individual capabilities is used.

Such API or at least such possibilities in the one or the other way would be very great.

Best regards,
Klaus

**Comment by toji** [comment]
New API addresses this issue. Repeated calls to `VRDisplay.requestPresent()` allow you to update the `VRLayer` dictionary without exiting VR presentation mode.
