### ISSUE TITLE
Entering fullscreen mode stops working after doing it a few times (windows 8.1).

### ISSUE THREAD

**Issue by fthr** [toji/chrome-webvr-issues#29]
(as demoed at WebVR superfriends meeting)

OS: Windows 8.1
Gfx card: NVIDIA GeForce GT 755M

Using the "direct mode only" build from march 29.

After entering the fullscreen mode a few times the fullscreen mode stops working.

When this happens, the DK2  does switch to the blue light, but the image seen inside the HMD is a frozen screenshot that has remained from the moment just before you exited fullscreen the last time.

Once this starts to happen, the only way to make it work again is to restart the browser, refreshing the tab does not help. 

Steps to reproduce:
1. Go to: http://vizor.io/yrx7nGxLQcge with DK2 connected and in direct mode
2. Wait for the scene to preload and play
3. Press the fullscreen button to enter VR mode, and esc to come out
4. Repeat going to fullscreen until the freezescreen happens (usually about 6-8 times on my system)

**Comment by capnmidnight** [comment]
I've seen this behavior on Windows 8.1 with GeForce GTX 570 as well. In my case, steps 3 and 4 had a "reload the page" step in between. When the bug is triggered, I have to restart the browser completely.

**Comment by fthr** [comment]
Tried the new build from April 26, this bug still persists. Now it crashes slightly differently. It crashes with the same frequency, about 4-6 times into fullscreen mode, but instead of freezing the frame in HMD, the HMD now goes out of fullscreen mode and the whole browser crashes on the laptop screen, giving a plain white window (screenshot attached). On the previous build, the browser didn't crash, one could keep using it, just not in fullscreen mode.

![chromium_crash_bug](https://cloud.githubusercontent.com/assets/6809021/7367948/3747f10a-edac-11e4-9c80-617964dd07c6.jpg)

Bonus screenshot: managed to get this crash once as well, looks kinda cool :)

![chromium_crash_2](https://cloud.githubusercontent.com/assets/6809021/7367965/57a001ae-edac-11e4-874a-08f70742c180.jpg)

**Comment by toji** [comment]
Yeah, I've seen that artifact pop up from time to time. I've got a couple of ideas as to what it might be, but haven't had the time to pursue them yet.

Now that extended mode is working again this bug is pretty high on my TODO list. Hopefully it turns out to be something simple.

**Comment by toji** [comment]
This issue is now moot since the new API doesn't rely on Fullscreen. If you see similar behavior in the new builds please report a new issue!
