### ISSUE TITLE
Support Google Cardboard

### ISSUE THREAD

**Issue by toji** [toji/chrome-webvr-issues#3]
Yup.

**Comment by ReedL** [comment]
The December 30th build seems to work pretty well on Nexus 4/5.0.1, including tapping to emit a mouse click, but it's awkward to reach through the nose gap with a finger. I'd like to request support for the magnet pull being mapped to mouse click as part of Cardboard support (if it isn't already on your todo list). Thanks!

**Comment by toji** [comment]
That's the current plan. I've got about 50% of the code written, and am currently just trying to figure out where in Chrome is the best place to emit the synthetic tap.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
