### ISSUE TITLE
Newest ChromeShell (Android) build immediately crashes on startup

### ISSUE THREAD

**Issue by hh3m** [toji/chrome-webvr-issues#30]
Hi Brandon,

Just wanted to let you know that the newest ChromeShell WebVR build for Android immediately crashes on my Samsung Galaxy Note 4 (European model) on startup.

Only the message "ChromeShell stopped" is shown.

I've reverted back to the previous version, which works great :)

Any ideas?

**Comment by toji** [comment]
Not sure, especially if it doesn't provide any further hints about why it died. I've made some pretty extensive "under the hood" changes since that version was posted, so it's probably beneficial for me to upload another one soon and see if it's still crashing for you.

**Comment by hh3m** [comment]
No other messages or errors are shown.

Is there a Chrome flag I can set to show more error messages?

I think I wouldn't be the only one waiting for a new more stable Android release.

**Comment by toji** [comment]
I've just uploaded a new Android apk: https://drive.google.com/open?id=0BzudLt22BqGRbVU2cVZiU05XeW8&authuser=0 Give it a try and see if it fixes the crashing for you!

**Comment by hh3m** [comment]
I've just tested the new Android build with some MozVR examples. It works flawlessly, many thanks Brandon!

Overall, it feels much more stable to use, and didn't crash one time.

This is probably not the right place to ask, but can you share with use some kind of "roadmap" for WebVR support in Chrome(mium)? Maybe through your blog?

Some things that come to mind are:
- Latency, latency, latency
- WebVR support in Chromium nightly
- New builds for Mac OS X (and Linux)

**Comment by toji** [comment]
Good to hear that improved it for you!

I definitely need to do an updated roadmap. I'm waiting till a few things solidify on this end so that I can talk about more concrete plans instead of hopes and dreams. :)
