### ISSUE TITLE
chromium crash with krpano parent or nested layers

### ISSUE THREAD

**Issue by VirtualTuur** [toji/chrome-webvr-issues#31]
Hi, I experience chromium crashes when you use nested layers or parents in Krpano.
Nested layers like:
<layer name=".... >
    <layer name=".../>
</layer>

or

the old parent/child system 
<layer name="test" parent="layer[test2]"... />

It crashes when you use one of these anywhere in your project. Vr mode or not.. it crashes.

Tuur

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
