### ISSUE TITLE
S6 edge - WebVR API not supported

### ISSUE THREAD

**Issue by zproxy** [toji/chrome-webvr-issues#33]
ChromeShell_Cardboard_SDK_0.5.3.apk Apr 21 Brandon Jones
reports on http://media.tojicode.com/webvr-test/
WebVR API not supported
howcome?

**Comment by zproxy** [comment]
would there be something to look for in logcat to understand why it is unavailable?

**Comment by toji** [comment]
Navigate to "about:flags" and find the "Enable WebVR" setting. Once that's enabled the API should show up.

**Comment by zproxy** [comment]
thanks. you may want to make sure to enable it by default for those of us who miss the flag :)

**Comment by toji** [comment]
Yeah, I know it's easy to miss. I'm trying to bring the experimental builds closer to what will actually launch in Chrome initially, so it's probably best to get everyone used to the flag now.
