### ISSUE TITLE
Android content_shell_apk build failed

### ISSUE THREAD

**Issue by sarathsi** [toji/chrome-webvr-issues#34]
Android content_shell_apk build failed.
Build Error:
../../content/shell/browser/shell.h:123:8: error: 'void content::Shell::EnterFullscreenModeForTab(content::WebContents*, const GURL&)' marked override, but does not override 

Patch needed to FIX this:
content/shell/browser/shell.cc
 void Shell::EnterFullscreenModeForTab(WebContents\* web_contents,
-                                      const GURL& origin) {
-                                      const GURL& origin,
-                                      int display_id) {
  ToggleFullscreenModeForTab(web_contents, true);
  }

content/shell/browser/shell.h
   void LoadProgressChanged(WebContents\* source, double progress) override;
 #endif
   void EnterFullscreenModeForTab(WebContents\* web_contents,
-                                 const GURL& origin) override;
-                                 const GURL& origin,
-                                 int display_id) override;

**Comment by toji** [comment]
Sorry, I've been focusing on getting the basic sensor polling into Chrome top-of-tree for Android and I've let this branch bit-rot some. (Checking out the webvr_live branch should get you a building branch, but it won't have any distortion handling.)

I'm out of office for a while, so unfortunately I can't fix this right away, but I'll update this ticket when I've gotten around to it.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
