### ISSUE TITLE
Android chrome_shell_apk build failed (/third_party/cacheinvalidation)

### ISSUE THREAD

**Issue by sarathsi** [toji/chrome-webvr-issues#35]
chrome_shell_apk Build error:

[144/2744] ACTION Generating Java code from protobuf files in ../../third_party/cacheinvalidation/src/proto
FAILED: cd ../../third_party/cacheinvalidation; ../../build/protoc_java.py "--protoc=../../out/Release/android_protoc" "--proto-path=../../third_party/cacheinvalidation/src/proto" "--java-out-dir=../../out/Release/java_proto/cacheinvalidation_proto_java/src" "--stamp=../../out/Release/java_proto/cacheinvalidation_proto_java/src.stamp" ../../third_party/cacheinvalidation/src/proto/android_channel.proto ../../third_party/cacheinvalidation/src/proto/android_listener.proto ../../third_party/cacheinvalidation/src/proto/android_service.proto ../../third_party/cacheinvalidation/src/proto/channel_common.proto ../../third_party/cacheinvalidation/src/proto/client.proto ../../third_party/cacheinvalidation/src/proto/client_protocol.proto ../../third_party/cacheinvalidation/src/proto/java_client.proto ../../third_party/cacheinvalidation/src/proto/types.proto
Traceback (most recent call last):
  File "../../build/protoc_java.py", line 68, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../build/protoc_java.py", line 51, in main
    + args)
  File "../../build/android/gyp/util/build_utils.py", line 158, in CheckOutput
    raise CalledProcessError(cwd, args, stdout + stderr)

**Comment by toji** [comment]
There's some dependencies in Chrome that need to be straightened out. I'm in the process of fixing it upstream in the Chrome repo, but it will take a few days to get fixed. I'll update this ticket when it should build again.

**Comment by toji** [comment]
Doing a quick bug sweep. This should be resolved now.
