### ISSUE TITLE
Chrome doesn't follow the VRPositionState spec

### ISSUE THREAD

**Issue by dmarcos** [toji/chrome-webvr-issues#36]
I'm using the OSX build downloaded from here: 

https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ#list

When a positional tracker is not present the VRPositionState must containt hasPosition === false and position must be null. As stated in the latest spec:

http://mozvr.github.io/webvr-spec/webvr.html#dom-vrpositionstate-hasposition

Chrome always return a position even if there's no positional camera connected and the hasPosition attribute is never set.

**Comment by toji** [comment]
I need to go back and check to see what my implementation is doing, but what are your thoughts on something like neck modeling? If the headset can guess at basic head position based on rotation, that still feels like something worth exposing. I'm doing that with my cardboard builds, at least.

**Comment by dmarcos** [comment]
I don't have a strong opinion If estimating position based on head orientation would be appropriate. I think this is a better question for @vvuk  

I discovered the difference in the implementations when I realized that VR mode of https://www.shadertoy.com/ was not working on Firefox. Their code was assuming always a position from the sensor, which only Chrome provides. I think the hasPosition and position attributes of the spec are redundant and confusing for the developer. Can we get by with just the position attribute that will be null if the info is not available? 

http://mozvr.github.io/webvr-spec/webvr.html#dom-vrpositionstate-hasposition

**Comment by toji** [comment]
I've felt the same for a while, that we should just use a null position to indicate lack of data, but had assumed that Firefox had a decent reason for adding it. I wouldn't mind at all if the booleans were removed.

**Comment by toji** [comment]
I'll try and put out a build soonish that handles lack of position properly, by the way. I'm in the middle of a big refactoring of the display side of things, which has prevented me from releasing new builds for a while, but I may be able to squeeze that in.

**Comment by toji** [comment]
New spec renders this issue moot. Closing.
