### ISSUE TITLE
New desktop build for Oculus SDK 0.7 (or 0.6)

### ISSUE THREAD

**Issue by jbroberg** [toji/chrome-webvr-issues#37]
Is it possible to get a new Windows Chromium build that supports a more recent Oculus SDK? Even a build against the 0.6 SDK should allow folks running the 0.7 runtime.

The current build does not detect the oculus at all (which is expected) on Windows 10 / SDK 0.7 since it's built against the Oculus 0.5.0.1 SDK.

Many thanks for all the great work.

**Comment by toji** [comment]
I've had the input portion working with 0.6/0.7 for a while now, that was easy. Unfortunately I've been hitting a wall with getting Chrome to output the the HMD with their new compositor system. Any time I attempt to submit a frame the browser deadlocks.

This is unquestionably an issue with how Chrome is rendering, though I'm still not sure what part of it is causing the problem. I can run any other Rift apps just fine, and can create test code outside of Chrome that renders correctly as well. In fact, I can spin up a secondary window within Chrome and have it output to the Rift correctly as well, but when any time I try to take results from Chrome's graphics and display them on the Rift I deadlock.

I'm going to keep working at it, and as as soon as I identify the issue I'll be able to either work around it or let Oculus know so they can account for it (I doubt that will be necessary, though.) It's mostly going to take a couple of days time where I can focus exclusively on VR work, and I haven't had that recently. I'll try to squeeze something in next week.

**Comment by andresiraola** [comment]
@toji Are you able to create the swap texture set correctly? I took your experimental branch for chromium and tried to adapt it to work with Oculus SDK 0.7 direct-mode but I had no luck creating those textures :(. I get access violation when calling ovr_CreateSwapTextureSetGL. Did you have any luck getting this to work? How did you do it?

**Comment by toji** [comment]
Quick update: I've worked out the cause of the deadlock issue I mentioned earlier and am hoping to have new 0.7 builds available in ~1 week.

**Comment by oscarbg** [comment]
Still coming soon?

**Comment by toji** [comment]
*sigh* Yes, but not as soon as I had hoped.

I've suddenly found myself in the process of purchasing a home, which takes up far more time and energy than it has any right to. That's great for me, but unfortunately it comes at the expense of time to work on the WebVR build. I'm still working at it when I have a chance, but it's going to take longer for me to pull it all together than I thought. Sorry for the delay, and thanks for your patience!

**Comment by ToJans** [comment]
@toji No worries, even though we're looking forward to the new version, I assume we all understand that purchasing a new home has a way higher priority; congratulations!

If you push your current branch for the 0.7 SDK, maybe some of us might have the ability to figure out how to get it up & running? Anyway, that's just a side thought. Best of luck with your new home!

**Comment by oscarbg** [comment]
@toji don't worry and congratulations..
and if you want that I talk with Larry of Sergey so they can allow you more time on this project say me :-)

**Comment by toji** [comment]
@ToJans: You can actually see the latest code at https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_openvr, though it's in a rough state. And yes, the branch is called openvr but it's actually the latest implementation of both APIs. I'm going to make this the one true WebVR branch once I get the display garbage sorted. I don't really have the bandwidth to support questions about the state of the code right now, sorry, but the main bit that you'd want to look if you're attempting to fix things is vr_compositor_oculus.h/cc (Note that in this branch ANY WebGL content will attempt to display on the HMD)

**Comment by toji** [comment]
A 0.8.0.0 SDK build is now available at the usual link: https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ&usp=sharing#list

Still has some bugs to work out, but it at least gets us back up and running with the latest SDK.
