### ISSUE TITLE
Chromium OpenVR build crashes when reloading in VR

### ISSUE THREAD

**Issue by tbalouet** [toji/chrome-webvr-issues#38]
Bug occured with the latest Chromium_Win_OpenVR_0.9.10 build on Windows 8.1

Reprosteps : 
- Have a HTC Vive connected to the computer and working
- Launch WebGL site (beloola.com or vizor.io)
- Launch VR mode (Settings->Enter VR in beloola or fullscreen mode in vizor)
- Press F5

Expected result : 
The page should reload and leave VR mode quietly

Actual result : 
The page reload, after a couple of seconds the browser show crash, if you press F5 we get the "WebGL hit a snag" message. Clicking reload then works.

**Comment by toji** [comment]
Thanks for the report. I've got a rough idea of what might be causing this.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
