### ISSUE TITLE
Chromium for android crashes

### ISSUE THREAD

**Issue by varunsaravagi** [toji/chrome-webvr-issues#39]
I downloaded the ChromePublic_Tango_1.19.apk and installed it on Nexus 6. However, it does not open. It crashes when I try to open it.

**Comment by toji** [comment]
The Tango build is only supported on Project Tango devices. Please try the ChromePublic_Cardboard_....apk instead. (Or download Chrome Dev fromthe Google play store, which also supports WebVR when enabled through about:flags)
