### ISSUE TITLE
Eyes swapped in latest 0.8 build with DK2

### ISSUE THREAD

**Issue by brianpeiris** [toji/chrome-webvr-issues#40]
This simple scene reproduces the problem: https://output.jsbin.com/pewuno/6/
It works correctly in Firefox Nightly.

**Comment by omgitsraven** [comment]
Seconded; happening for me too, Oct 23 WebVR build, Win 7 64-bit. I knew something was wrong with the eye positions but that jsbin demonstrates it perfectly. Works correctly in Firefox Nightly for me too.

**Comment by toji** [comment]
Thanks for the report. Out of curiosity, do you see it swapped on http://media.tojicode.com/q3bsp/ as well? I didn't see that, but I also wasn't looking for it and it's not always readily apparent with larger environments.

Unfortunately I'm in the middle of a move and so my DK2 is packed away temporarily, so I won't have a chance to test this myself for another ~week. If it's consistent across all VR sites, though, I'll just invert the eye offset and rebuild.

**Comment by brianpeiris** [comment]
Yup. q3bsp has the issue as well. Thanks!

**Comment by toji** [comment]
Okay, let me see if I can do a quick rebuild in the next day or so. If you
don't mind I'll link it here first so I can get a confirmation from you
that it's working as intended.

**Comment by brianpeiris** [comment]
No problem. Happy to help.

**Comment by toji** [comment]
Try this build out and let me know if it corrects the problem for you:  https://drive.google.com/file/d/0BzudLt22BqGRZHpLV3VHbFJZNkk/view?usp=sharing

**Comment by omgitsraven** [comment]
Perfect! Thank you!

**Comment by toji** [comment]
@omgitsraven: So it's working for you correctly then?

**Comment by omgitsraven** [comment]
Yes, it's working correctly now.

**Comment by brianpeiris** [comment]
:+1: Works for me as well. Thanks for the quick turnaround Brandon!

**Comment by toji** [comment]
Thanks for the confirmation! Main build list has been updated with the new build.
