### ISSUE TITLE
Contrast Too high

### ISSUE THREAD

**Issue by SeanHoey** [toji/chrome-webvr-issues#41]
Hey guys,

I am having a strange thing happening with my project. When i display it onto the Oculus the contrast seems to increase on Oculus but is fine on monitor.I have tried it on the Firefox and the contrast is fine.

I am using Oculus runtime version 0.8 and Re­release  Chromium_Win_Oculus_0.8.0.0.

I notice the contrast is slightly brighter in the Quake 3 example aswell.

**Comment by toji** [comment]
Should be fixed in the latest experimental build. Oculus was expecting an SRGB texture but Chrome doesn't render anything in SRGB, so I had to tweak things a bit.
