### ISSUE TITLE
Chrome crashes if I don't initialize vrcontrols in webvr-boilerplate

### ISSUE THREAD

**Issue by bnolan** [toji/chrome-webvr-issues#42]
I was getting a bug where chrome crashed 'oh snap' everytime i went into VR mode. I tracked it down to the case where if you don't initialize vrcontrols (and read sensor data I assume), chrome crashes on entering VR mode.

Repro steps:
- clone webvr-boilerplate
- comment out each mention of `controls`
- load index.html and enter vr mode
- oh snap

**Comment by bnolan** [comment]
Actually, even with the controls enabled, I'm still getting random crashes every few refreshes. How do I generate a stack trace to attach here?

Windows 8.1
GTX 750ti
Oculus drivers 0.8.0

**Comment by capnmidnight** [comment]
I had the same issue, random crashes when refreshing, and I eventually
figured out that it wasn't random, that it would always happen if I did not
hit escape to exit full-screen mode (and remove the Oculus Rift as the
target rendering device), before refreshing the page. If I do remember to
escape full-screen, then Chrome is much more stable during a refresh.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
