### ISSUE TITLE
Chromium do not get HTC Vive in device list

### ISSUE THREAD

**Issue by tbalouet** [toji/chrome-webvr-issues#43]
I got a HTC Vive dev kit and had it working (vive tutorial showing in the HMD, SteamVR icons all green).

I downloaded the Chromium build "Chromium_Win_OpenVR_0.9.10.7z", enabled WebVR in chrome://flags

But I can't launch any WebVR demo, and when I try this bit of code, all I get is an empty array:
```
function EnumerateVRDevices(devices) {
  console.log(devices);
}
navigator.getVRDevices().then(EnumerateVRDevices);
```

Is there anything I'm missing there?
Thanks!

**Comment by toji** [comment]
I'm curious: If you open Steam and launch the SteamVR tool so that the monitor is running when you start Chrome does that make a difference? Also, make sure you're running the beta version of the SteamVR app, which will include the latest runtimes.

**Comment by tbalouet** [comment]
Actually I was always having SteamVR launched when trying to use WebVR. And I forgot to put on the beta mode for SteamVR.
So I did that, and I tried to not launch the SteamVR app this time, and it made the trick. But that isn't the way I used to make it work before. Strange...
Anyway I'm closing the issue as not launching SteamVR seems to make it work. Do you know where we could drop a few lines on how to use Vive for VR at the moment? Could be helpful for future users

**Comment by toji** [comment]
Good question. We need a community Wiki or something. Hm... I'll see what I can do about that.

Ultimately users shouldn't have to do these little rain dances of "open this/close this" to make things work. (Although in this case I think it's maybe more likely that the switch to beta mode is what fixed your problem.) I suspect some of this is simply OpenVR still working towards a stable point, but I'll try and spend more time making sure that it can launch robustly from any number of initial states.

**Comment by tbalouet** [comment]
Maybe for now as only your build is supporting Vive, we could add those informations to your README or the frontpage of webvr.info?
And maybe the Beta version helped, but fact is I can't launch WebVR if SteamVR is already launched, even though it used to work back in october. Maybe they did an update on their side preventing WebVR from taking the output, or am I the only one having this problem?

**Comment by DougBlumeyer** [comment]
WebVR + Vive... halp. I got the beta version of SteamVR, running in the background. I got not just the Chromium build but the OpenVR one, have set the vr flag, open it. I can't get a single WebVR experience to work. best I get is a grey flash in the headset. anyone know what I'm missing?
