### ISSUE TITLE
Direct Mode

### ISSUE THREAD

**Issue by brentgreyling** [toji/chrome-webvr-issues#45]
I'm at the point now where forcing Extended Mode on 64-Bit Windows 10 with the latest Catalyst Drivers is impossible using Oculus Runtime 0.8.0.0. I know you have addressed this before but any light on the possibility of a Direct Mode build? Thanks!

**Comment by toji** [comment]
The Windows builds have been using Direct Mode exclusively for a little while now, since I think October. Please make sure you're testing with a recent build: https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ&usp=sharing#list

**Comment by brentgreyling** [comment]
I have been systematically up to date with my Graphics Drivers, Oculus
Runtimes as well as your Chromium releases.

Admittedly, there was a Direct Mode zip a few releases back
(Chromium_WebVR_Win_SDK_0.5.0.1_Direct_Mode_Only.7z) that I never did try
at the time though.

Therefore I can only think it must be something specific to my setup as no
build to date has opened in Direct Mode for me while other Direct Mode
demos etc. have presented no unresolvable problems.

Anyhow, ALL builds are much appreciated - Thank you.





On Tue, Jan 19, 2016 at 7:56 PM, Brandon Jones <notifications@github.com>
wrote:

> The Windows builds have been using Direct Mode exclusively for a little
> while now, since I think October. Please make sure you're testing with a
> recent build:
> https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ&usp=sharing#list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toji/chrome-webvr-issues/issues/45#issuecomment-172933463>
> .
>



-- 
*Regards*,

   *Brent Greyling*
<https://about.me/brentgreyling>
