### ISSUE TITLE
HTC vive pre Failed to recalculate device parameters.Dpdb.recalculateDeviceParams_ 

### ISSUE THREAD

**Issue by wizztjh** [toji/chrome-webvr-issues#47]
Chrome htc vive not detection orientation 
```
Pixel width: 1920
dpdb.js:111 Pixel height: 1200
dpdb.js:153 No DPDB device match.
dpdb.js:74 New device parameters:
dpdb.js:75 null

Fetching DPDB...
device-info.js:107 Using fallback iOS device measurements.
webvr-manager.js:69 Using the Cardboard I/O 2014 viewer.
webvr-manager.js:217 Mode change: 0 => 1
dpdb.js:53 Successfully loaded online DPDB.
dpdb.js:72 Recalculating device params.
dpdb.js:109 User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2663.0 Safari/537.36
dpdb.js:110 Pixel width: 1920
dpdb.js:111 Pixel height: 1200
dpdb.js:153 No DPDB device match.
dpdb.js:74 New device parameters:
dpdb.js:75 null
dpdb.js:83 Failed to recalculate device parameters.Dpdb.recalculateDeviceParams_ @ dpdb.js:83
http://borismus.github.io/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by toji** [comment]
It looks like you're only getting the fallback to the WebVR polyfill, which means your headset isn't being detected at all. Did you enable webvr in about:flags?

Also, there's some new builds being released today (along with a new spec) that you can test to ensure it detects your headset. Get the builds here: https://drive.google.com/folderview?id=0BzudLt22BqGRbW9WTHMtOWMzNjQ&usp=sharing#list and try the samples here: https://toji.github.io/webvr-samples

Be aware that these builds are NOT backwards compatible with the old API, though, so your site will not work without some updates. Read more about that here: http://blog.tojicode.com/2016/02/moving-towards-webvr-10.html

**Comment by wizztjh** [comment]
It works after I use your VR demo and enable the flag.
Thanks @toji for all the hard work!!! The room scaled vr demo is awesome. I turn my head around and the webvr block is right infront of me. Then my reflexes kicks in.
