### ISSUE TITLE
Have to close Chrome between each demo

### ISSUE THREAD

**Issue by omgitsraven** [toji/chrome-webvr-issues#48]
I'm on Win7 64-bit, Oculus DK2, SDK  0.8.0.0, Chromium WebVR build 51.0.2663.0
1. Open any page that presents to the HMD (i.e. http://toji.github.io/webvr-samples/03-vr-presentation.html )
2. Enter VR. Everything works normally.
3. Press the browser's "back" button, **WITHOUT** first clicking 'exit VR'. The last image on the HMD stays there, frozen (which is already a bit of a bug)
4. Navigate to another page with HMD support (or even the same one again).
5. Enter VR. The page acts like it was successful, but the frozen image from last time is STILL there instead of the live view you should be seeing. It will stay there until you quit Chromium.
6. Quit Chromium. The HMD finally goes black.
7. Launching Chromium again will now allow you to repeat the process.

**Comment by capnmidnight** [comment]
I believe this is the same issue as this: https://github.com/toji/chrome-webvr-issues/issues/29

**Comment by omgitsraven** [comment]
Similar result, but that one was happening unpredictably after a few tries of doing the same thing (which I also remember happening in previous builds), whereas this now happens consistently every time (and can be worked around with the 'exit VR' button).

**Comment by capnmidnight** [comment]
It's basically any action that causes the page to reload while in full-screen mode. That could be navigating or explicitly reloading the page. Perhaps as a work around, we should be adding a call to exit full screen mode as the page is unloading.

**Comment by cvan** [comment]
Just dropping a link to my comment in the three.js PR: https://github.com/mrdoob/three.js/pull/8221/files#r54668602

**Comment by cvan** [comment]
The issue here is a bug that is requiring `VRDisplay.exitPresent()` to be explicitly called to stop presenting (`VRDisplay.requestPresent` is how to "enter VR mode" in the new WebVR API).

If you don't, you'll have to relaunch Chromium.

Even when I do explicitly "exit VR mode" (call `VRDisplay.exitPresent()`), I notice I still have to relaunch Chromium after every page load or two wherein I enter VR (with the new API).

**Comment by toji** [comment]
To be clear: you can definitely work around this issue by manually exiting VR mode before you navigate *but* this is absolutely a bug in the Chrome builds. Implementations should cleanly shut down VR-related systems upon page navigation.

**Comment by jbaicoianu** [comment]
Related to this, I tried calling vrdisplay.exitPresent() in window.onunload, and it seems like this is also unreliable.  It seems like exitPresent() takes some amount of time to complete, and if the page finishes unloading before exitPresent() finishes, the previous scene remains on the HMD.

Adding a forced synchronous delay of half a second or so after calling exitPresent() seems to help a bit, but still requires a chrome restart after a few tries.  exitPresent() does return a promise, but AFAIK there's no way to delay unload to wait for an async action to complete, right?

**Comment by jbaicoianu** [comment]
One more observation.  When I manually call exitPresent() the display goes black as expected, but the blue light on the HMD still stays lit until I close the browser.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
