### ISSUE TITLE
Flickering FPS (and stuttering) in Sample 4 but not in Sample 3

### ISSUE THREAD

**Issue by omgitsraven** [toji/chrome-webvr-issues#49]
When I run Sample 3 ("VR Presentation"), I get a totally constant 75 fps, no dips at all, and the world feels wonderfully smooth. (I'm on a DK2, so 75 is the correct FPS.)

When I run Sample 4 ("Simple Mirroring"), the FPS counter rapidly flicks back and forth from 71 to 79 fps (with a 75 in there occasionally), and there is visible stuttering if I slide my head horizontally (though it still appears smooth if I only rotate my head, so timewarp seems to still work).

![79fps](https://cloud.githubusercontent.com/assets/8540042/13412216/a9d76110-df0f-11e5-822f-fe715aed795c.jpg)

Occasionally there are pockets of solid 75fps (the right side of the graph above) but within a few seconds it goes back to cycling rapidly between 71, 75, and 79.

I'm running Windows 7 64-bit, with an Oculus DK2 and a GTX 970, running SDK 0.8.0.0 and Chromium WebVR build 51.0.2663.0

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
