### ISSUE TITLE
window.requestAnimationFrame not using vsync

### ISSUE THREAD

**Issue by jbaicoianu** [toji/chrome-webvr-issues#51]
It seems that when using window.requestAnimationFrame() the framerate in the WebVR builds is no longer locked to the refresh rate of the monitor.  For example, I'm seeing 690 fps on http://threejs.org/examples/#webgl_animation_cloth and 500fps on http://media.tojicode.com/q3bsp/ (I wish I'd been able to pull that sort of fps in q3a back in the day!)

vrDevice.requestAnimationFrame() is properly limited to the HMD's framerate, this only affects window.requestAnimationFrame()

(as a side note, I actually like having the ability to run rAF without vsync, the --disable-gpu-vsync option hasn't worked in some time and I miss being able to do full-speed tests.  So there's some small part of me which almost wants you to not fix this...)

**Comment by toji** [comment]
This has been fixed for a little while now. Try it with the lastest builds at https://webvr.info/get-chrome/
