### ISSUE TITLE
Norton Antivirus flags 'Suspicious.Cloud.7.EP' virus on all Chromium WebVR builds

### ISSUE THREAD

**Issue by vt5491** [toji/chrome-webvr-issues#53]
Norton Internet Security (anti-virus program) always flags the Chromium WebVR builds with:

Suspicious.Cloud.7.EP
Risk: High

You get this when extracting the zip or trying to run the binary.  It's flagging the dll's only.  I've gotten around this by explicitly excluding the extracted directory but it's still potentially worrisome.  I'm assuming it's a false positive, as I've never had any problems and [Norton has had this problem in the past](http://community.norton.com/node/709923).

This could simply be a Norton problem only, but I suppose it's worth asking if:
A) You, or anyone else, has previously reported this problem.
B) Are you building on a system that has been scanned for viruses and especially the presence of "Supsicious.Cloud.7.EP"?
C) I've always thought it strange that you have a zip within a zip.  I wonder if the virus program is just reacting to a zip in a zip?  OTOH, it generates the error when you execute the binary out of the zip, so that contradicts this theory.
D)  Is there anything "unusual" you do on you dll builds?

Like I said, it's probably all on Norton's side, but I've only ever had this with Chromium VR builds, and all Chromim VR builds have it.

**Comment by toji** [comment]
FYI: With the most recent Oculus build that I posted today I made sure to not make it a zip within a zip. I'd be surprised if that actually changed Norton's opinion of it, but if you could give it a try I'd appreciate it!

**Comment by vt5491** [comment]
Same thing.  Note, it won't just be the prefs.dll.  You'll exclude that and then it will report the error on another dll.  You just have to excude the entire directory. 

 Note how they say the file has been used by less than five people.  At first, you might just think that "Suspicious.Cloud" is just there code for a file than hasn't been used very often.  However, I almost always get low activity alerts on OSVR downloads as well -- but it doesn't flag this specific error, just "warning: this file is suspicious because "fewer than five people have downloaded it".

Filename: prefs.dll
Threat name: Suspicious.Cloud.7.EPFull Path: c:\vtstuff\downloads\extract_3\chrome-bin\51.0.2690.0\prefs.dll

____________________________

____________________________


On computers as of 
3/29/2016 at 11:20:11 PM

Last Used 
3/29/2016 at 11:22:12 PM

Startup Item 
No

Launched 
No

Threat type: Heuristic Virus. Detection of a threat based on malware heuristics.


____________________________


prefs.dll Threat name: Suspicious.Cloud.7.EP
Locate


Very Few Users
Fewer than 5 users in the Norton Community have used this file.

Very New
This file was released less than 1 week  ago.

High
This file risk is high.


____________________________


Source: External Media

Source File:
prefs.dll

____________________________

File Actions

File: c:\vtstuff\downloads\extract_3\chrome-bin\51.0.2690.0\ prefs.dll Removed
____________________________


File Thumbprint - SHA:
c1e6ef3afa92738006118637119b7cfa303ad15aee7f433bab6d55e363fa7e21
File Thumbprint - MD5:
Not available

![image](https://cloud.githubusercontent.com/assets/8662470/14133587/4fc8e31c-f605-11e5-92a8-2caad9aa1a3c.png)

![image](https://cloud.githubusercontent.com/assets/8662470/14133728/b78a5a7a-f606-11e5-92a8-973ec20cbe2e.png)

Since the file is now quarantined, I cannot start chromium:
![image](https://cloud.githubusercontent.com/assets/8662470/14133775/ee9be60a-f606-11e5-81cb-e95bb1bb9df8.png)

**Comment by vt5491** [comment]
I'm assuming it's a false positive, but it sounds real nasty otherwise.  From http://www.enigmasoftware.com/suspiciouscloud7ep-removal/

Suspicious.Cloud.7.EP Description
Suspicious.Cloud.7.EP is a high risk malware infection, which can devastate an affected computer. Detection of Suspicious.Cloud.7.EP by anti-virus software may also indicate that the computer is probably affected by a Trojan or similar PC infections. Suspicious.Cloud.7.EP adds itself to some of the files that the PC user stores on the computer and to specific programs that the PC user may have downloaded from the Internet. The main feature of Suspicious.Cloud.7.EP is that once it corrupts the victimized PC, it will start to stealthily attack the files and control network activity in case it's a password stealing Trojan. Suspicious.Cloud.7.EP can be the affected file or application that the computer user has downloaded from the Internet, or it may be the result of a virus that has already contaminated the PC. Suspicious.Cloud.7.EP are also able to steal a target PC user's personal information and download more malware threats onto the compromised PC. Suspicious.Cloud.7.EP rarely comes as a single infection; usually it's a component of more advanced malware threats.

**Comment by vt5491** [comment]
Well I just tried it on my desktop, which has McAfee and no problems.

So either this is a Norton only thing, or there's just something about my laptop.

So at this point, it doesn't look like a universal problem i.e it's just specific to me.  So unless, you want to pursue this further, I think we can go ahead and close this.

**Comment by toji** [comment]
It seems like Norton is mostly concerned about the fact that it's a recently posted file from an unknown source (me) which has a low number of users. (They can't possibly track "Downloads" so what they really mean is "Less than 5 Norton Users have tried to run this exact binary.") I can see why that might trip their "suspicious binary" heuristics, but I feel like it's definitely a false positive. Even the name seems pretty generic: "Suspicious.Cloud", as in "Suspicious because it's from the cloud?"

The scary sounding description that you pulled up from the site is likely for an actual piece of malware that matched the same generic detection.

I don't know if there's anything I can do about this, since it really just sounds like Norton is being overly cautious. I promise that there's nothing intentionally malicious in my builds, though they may crash from time to time! :) Eventually the "fix" for this is just to get the feature into stable Chrome.
