### ISSUE TITLE
Video playback crashes Chromium Tab

### ISSUE THREAD

**Issue by fr-** [toji/chrome-webvr-issues#55]
Using the WebVR chromium build with the OculusSDK from Mar 29th 2016 or the one from Mar 20th 2016 the browser tab crashes when playing back video after decoding a couple (hundred?) of frames.

Can reproduce the issue using any 360° video on YouTube and letting it play for some time. Not sure if this is related to the build itself or a problem in the chromium snapshot used in the branch.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
