### ISSUE TITLE
Browser silent crash

### ISSUE THREAD

**Issue by pavelvasev** [toji/chrome-webvr-issues#56]
version: chromium_webvr_v1_win_oculus.7z of 6 april 2016 release 

Oftenly crashes silently, just disappearing. Here are 2 log files for example.

[chrome_debug-crash-example1.log.txt](https://github.com/toji/chrome-webvr-issues/files/219462/chrome_debug-crash-example1.log.txt)
[chrome_debug-crash-example2.log.txt](https://github.com/toji/chrome-webvr-issues/files/219461/chrome_debug-crash-example2.log.txt)

**Comment by toji** [comment]
The logs are interesting, thanks! Not sure what the exact cause is but there's at least a couple of things I can see that are worth looking at.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
