### ISSUE TITLE
submitFrame kills chrome page

### ISSUE THREAD

**Issue by pavelvasev** [toji/chrome-webvr-issues#57]
version: chromium_webvr_v1_win_oculus.7z of 6 april 2016 release 

During call of submitFrame() without arguments AND without sometime previously calling getPose(), the page crashes and chrome shows "Oops something wrong happened" blank page.

**Comment by toji** [comment]
Thanks for the report. I think I know why that might be happening. I'll try to fix it ASAP.

**Comment by toji** [comment]
This should have been fixed as of a few weeks ago. Try it with the latest builds from https://webvr.info/get-chrome!

**Comment by pavelvasev** [comment]
Thank you!

**Comment by MiiBond** [comment]
Hey. I'm seeing this exact issue in the current build (July 6th) as well as the previous, June 30th one. Has this bug been re-introduced?

**Comment by toji** [comment]
I hope not, but I'll look into it. Any particular page you're seeing it on?

**Comment by MiiBond** [comment]
It's actually code for work which I can't share but I've been banging my head against the wall all day trying to figure out why Chromium was crashing. Then I found this post and tried making sure that getPose was called before submitFrame and it immediately started working.

**Comment by MiiBond** [comment]
I'm using the Three.js VRControls and VREffect. As long as VRControls update is called once before rendering the first VR frame, everything is cool. Otherwise the browser crashes every time.

**Comment by toji** [comment]
I didn't do anything for this bug specifically, but could you try the new build that I uploaded today? (I pushed a new one around 3:50 PST.) It touches some code around the crashing call and I'm curious if it just happens to fix it for you.

**Comment by MiiBond** [comment]
Looks like it still crashes. Sorry.

**Comment by toji** [comment]
No worries! I'll dig into it more purposefully soon.
