### ISSUE TITLE
window.onvrdisplaypresentchange does not fire on Android

### ISSUE THREAD

**Issue by capnmidnight** [toji/chrome-webvr-issues#58]
# Builds being used:
- Android: Feb 29th
- Windows: Apr 6th for Oculus Rift
# While entering full-screen

On Android, the event `onvrdisplaypresentchange` on the window object (https://mozvr.github.io/webvr-spec/#interface-window) does not fire after calling `requestPresent()` and entering the VR view.

Additionally, the `document.fullscreenElement` updates to the canvas element passed as the `source` property of the options parameter to `requestPresent()`.

Finally, it also suppresses the `onfullscreenchange` event. The only way to tell if the screen is in fullscreen "VR" mode is check the `document.fullscreenElement` value and to remember that the Promise from `requestPresent()` resolved.

On Windows the `onvrdisplaypresentchange` event fires after `requestPresent()` as expected. The `document.fullscreenElement` does not change and remains `null`.
## Desired result

Android should fire `onvrdisplaypresentchange` after `requestPresent()` has succeeded. `onfullscreenchange` should not fire. The value of `document.fullscreenElement` should not change.
# While exiting full-screen

On Android, hitting the "back" button will cause websites in fullscreen mode to exit fullscreen. Use the application switcher to change apps away from the fullscreen site and then back also causes fullscreen mode to be removed. But neither `onvrdisplaypresentchange` or `onfullscreenchange` fires, though the fullscreen mode does indeed cancel, making the address bar visible. The value of `document.fullscreenElement` resets to null.

On Windows, hitting `ESC` on the keyboard does not cause a change in fullscreen state, and the aforementioned events also do not fire.
## Desired result

Android should fire `onvrdisplaypresentchange` after the back button has been pressed, or the user uses the application switcher to switch out and then back in. `onfullscreenchange` should not fire. The value of `document.fullscreenElement` should not change.
# Workaround

```
var wasFullscreen = false;
function checkFullscreen(){
    var isFullscreen = !!document.fullscreenElement;
    if(wasFullscreen !== isFullscreen){
        window.dispatchEvent(new Event("vrdisplaypresentchange"));
        wasFullscreen = isFullscreen;
    }
}

function animate(dt){
    requestAnimationFrame(animate);
    if(isMobile) // <-- again, an exercise left to the reader
        checkFullscreen();
}

requestAnimationFrame(animate);
```

**Comment by toji** [comment]
Thanks for the detailed report! I knew about the issue with `vrdisplaypresentchange` not firing, didn't know `fullscreenchange` was being suppressed. It's on the TODO list, though it hasn't been as high of a priority as it probably should be simply because the Polyfill handles mobile devices pretty robustly at the moment.

**Comment by capnmidnight** [comment]
It might be helpful to add info to the spec doc about how these events are supposed to occur. IDK if one would want fullscreenchange to fire for devices with hasExternalDisplay = false or not. Perhaps that makes sense, or perhaps it just overcomplicates things to have two different "the screen is full" events for one display.

Alas, these are all just more symptoms of not having a real sense of how many displays are hooked up to the computer from client code. It doesn't make a lot of sense to say that the *window* has gone full-screen. The window is a container for a document, the document is a container for the canvas, it's the canvas that has gone full-screen, or is being presented. It ultimately would make sense to say that a particular *display* has received an exclusive element.

But I suspect is something like that is never going to happen, to help minimize the diversity of information that can be used to fingerprint users.

**Comment by brianchirls** [comment]
Regarding the suppression of `fullscreenchange`, it's worth having a look at this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=606177

It was filed for Linux, but I'm seeing it on OSX too. So maybe it's on Android as well.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
