### ISSUE TITLE
Vive room-scale init pose

### ISSUE THREAD

**Issue by arturitu** [toji/chrome-webvr-issues#59]
I have a problem with pose in room-scale with Vive. With the last build (Apr19) sometimes works well but sometimes init in a wrong position into the room (if you reload sometimes or do you change the headset position at start sometimes happens). (I have tested with your 05-room-scale.html) in my three.js based example doesn't work. Is it a problem of how the pose is initialized now? because with the Apr4 OpenVR build does not happens.

**Comment by toji** [comment]
Should be fixed in the latest build. May still initialize wrong but the right values will be pushed to the StageParameters when they become available.
