### ISSUE TITLE
Can't load any samples on chrome

### ISSUE THREAD

**Issue by db10101** [toji/chrome-webvr-issues#60]
I receive the error "ERROR: Your browser supports WebVR but not the latest version. See webvr.info for more info"

**Comment by db10101** [comment]
Definitely have the latest build

**Comment by nhirata** [comment]
I'm experiencing the same thing with the latest oculus runtime version.  I think it might be because of the change in runtime.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
