### ISSUE TITLE
Resizing window while presenting VR stops further VR updates

### ISSUE THREAD

**Issue by brianchirls** [toji/chrome-webvr-issues#61]
To replicate:
1. Open any [sample](http://toji.github.io/webvr-samples/) that uses WebVR 1.0
2. Enter VR
3. Resize the main window

The HMD will receive no further frame updates after this point, even if you exit and re-start VR presentation. Reloading the page or even opening a new tab doesn't fix it. You have to exit and re-start the browser. It doesn't matter if you try Advanced Mirroring, Simple Mirroring or no mirroring at all.

I've tried this with Oculus Rift DK2 and 1.3 drivers. Haven't tried with Vive.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
