### ISSUE TITLE
Update a build for mac?

### ISSUE THREAD

**Issue by vellow** [toji/chrome-webvr-issues#62]
It seems build for mac have not been updated for a long time.  Would It be a new build for mac or is there any trouble meet..

**Comment by toji** [comment]
This is, sadly, not an issue that I can control. The latest Oculus SDKs are only available for Windows, and the Chrome code that I'm using now relies on functionality that's only available in newer SDKs. It seems like OpenVR can build on OSX, but I've yet to have any luck actually getting it to recognize a headset. So for now it's effectively Windows only until there's official support from the underlying SDKs. As for when that will happen... https://youtu.be/ijyBMpm2bqQ?t=4m4s
