### ISSUE TITLE
Gamepad buttons not available

### ISSUE THREAD

**Issue by kschzt** [toji/chrome-webvr-issues#66]
Can't seem to get the Gamepad buttons visible via the Gamepad API in VR Chromium, just getting an empty array. Tried using the Rift controller as well as a standard XBOX 360 controller (that shows up in a regular Chrome as "Standard Controller").

None of the `axes` do anything either.

```
> navigator.getGamepads()[0]
< Gamepad {id: "Rift (Vendor: 2833 Product: 0031)", index: 0, connected: true, timestamp: 0, mapping: ""…}
	axes: Array[12]
	buttons: Array[0]
	id: "Rift (Vendor: 2833 Product: 0031)"

> navigator.getGamepads()[1]
< Gamepad {id: "Unknown Gamepad (Vendor: 2833 Product: 0031)", index: 1, connected: true, timestamp: 0, mapping: ""…}
	axes: Array[12]
	buttons: Array[0]
	id: "Unknown Gamepad (Vendor: 2833 Product: 0031)"
```

**Comment by toji** [comment]
Those two gamepads are "fake", and created when the Rift identifies itself as a two separate gamepad-like devices for some reason. I thought I had filtered those out of the newer builds, though. Are you using the latest executables from WebVR.info/get-chrome?

**Comment by kschzt** [comment]
Sorry, I had missed the latest update. Apologies :)

**Comment by toji** [comment]
No worries! This behavior confused the hell out of me too for a while.
