### ISSUE TITLE
How about adding a dynamic loading layer ?

### ISSUE THREAD

**Issue by shaoboyan** [toji/chrome-webvr-issues#67]
Hi, Brandon
  As I learn from the WebVR implementation based on chromium [here](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_1), I found that the implementation need include *.so in third_party.
  Does this mean if there are more platforms need to support by chromium webvr, the more .so need to be included in compiling and linking phase ? 
  So why not adding a dynamic loading layer and keep one vr-sdk(e.g. openvr.so or simulated vr) as backup? I think this will reduce the binary size and improve the scalability.
  And I'd like to help implement this feature if you agree :) @toji

**Comment by toji** [comment]
My understanding from talking with folks from Valve is that this particular library is pretty thin and mostly facilitates managing an IPC connection to their VR service. The Oculus SDK functions similarly. I definitely want to defer as much VR-specific initialization as possible, but wonder if it wouldn't have diminishing returns in this case. Still, I'm not opposed to the idea if it proves worthwhile.

**Comment by shaoboyan** [comment]
@toji, thx for your kindly explanation and response. Since I'm working on a web runtime [crosswalk](https://crosswalk-project.org/), I'd like to try this idea on the runtime and give some further response.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
