### ISSUE TITLE
"Sorry, chrome.exe is taking a while to load"

### ISSUE THREAD

**Issue by ruofeidu** [toji/chrome-webvr-issues#68]
Windows 10, Oculus Rift DK2, Runtime 1.4, Chromium build from https://webvr.info/get-chrome/ May 21st, WebVR flag set, unknown source set.

Navigate to https://mozvr.com/, when click on the button, chromium reported "Sorry, chrome.exe is taking a while to load" and it kept waiting. I tried many other websites and it was the same.

Thanks!

**Comment by ruofeidu** [comment]
My fault, it works perfectly with https://webvr.info/samples/ 
I think we should mention the WebVR 1.0 samples in the README FIRST.

Thanks!

**Comment by ssaroha** [comment]
I am facing this same issue.
here is my config:
Windows 10, 
Oculus Platform SDK 1.6 
Chromimum build from https://webvr.info/get-chrome/ July 29th, Web
webvr flag set in browser
"unknown source allowed" in oculus

when i navigate to https://toji.github.io/webvr-samples/02-stereo-rendering.html
I can see the browser detecting the HMD, and rendering moves in the browser as i move my rift around.

But when i try to view this experience inside my oculus it always shows message:
"Sorry chrome.exe is taking a while to load."

**Comment by ssaroha** [comment]
@toji any ideas, should i open a separate issue.

Thanks!

**Comment by aearanky** [comment]
I am also facing the same issue.
Oculus consumer version cv1 and 
here is my config:
Windows 10,
Oculus Platform Runtime SDK 1.9
Chromimum build from https://webvr.info/get-chrome/ Oct 29th, Web
webvr flag set in the chromium browser
"unknown source allowed" in oculus

Tried the same on firefox developer edition.

when i navigate to https://toji.github.io/webvr-samples/02-stereo-rendering.html
I can see the browser detecting the HMD, and rendering moves in the browser as i move my rift around.

But when i try to view this experience inside my oculus it always shows message:
"Sorry chrome.exe is taking a while to load."

Can someone please post a solution?

**Comment by ruofeidu** [comment]
Hi, I just tried my cv1 with the sdk 1.9.0 on Windows 10 with a GTX 1080.

These demos work for me:

https://webvr.info/samples/04-simple-mirroring.html
https://webvr.info/samples/05-room-scale.html

I guess the page you provided is not updated with the latest API calls :-)

**Comment by HeinPauwelyn** [comment]
Me too same problem

I'm using this browsers

* **Version Firefox nightly:** 55.0a1
* **Version Chromium:** 56.0.2910.0

**Comment by astraccia** [comment]
Downgrade your Nvidia driver to version 376, it worked for me. Take a look: https://stackoverflow.com/questions/43522265/sorry-firefox-exe-chrome-exe-is-taking-a-while-to-load-unresponsive-firefox/45484163#45484163

**Comment by danrossi** [comment]
I got this message. After clicking the beta channel I don't get the message but I don't get any presentation either. 

Clicking the saved chromium app in the menu launches new windows in chromium.  I had 382.05 installed. Will try and update the driver and try firefox also.

**Comment by danrossi** [comment]
ohh so Occulus doesn't work with Chromium build but Firefox will ?

**Comment by danrossi** [comment]
With the latest driver it worked in firefox straight away. After more updates and driver updates. 

 Chrome is now working but the camera was rotated around to the back when I have it set to look at the front not the back. 

There is severe latency issues and the picture is jerking. possibly need to create another ticket for that ?  Firefox was ok. 

My system crashed and the screen locked up trying to use the controller but , drivers are causing this windows machine to lock up and become unstable all the time.

**Comment by danrossi** [comment]
I'm now getting the same error in firefox. Possibly unrelated to chromium. It was just working on first launch.
