### ISSUE TITLE
work with HTC Vive?

### ISSUE THREAD

**Issue by alexiskattan** [toji/chrome-webvr-issues#69]
I tried the latest WebVR build with the HTC Vive and got it almost working.  The browser recognizes the moment of the headset.  However, the displays of the headset only show the default SteamVR white room and not what is displayed in the browser.

Is there a way to get the headset to display what is in the browser?

**Comment by toji** [comment]
It can display correctly, so there must be something specific to your setup that it doesn't like. Did you try with the samples at https://webvr.info/samples (specifically stuff like the "VR Presentation" sample.)

**Comment by alexiskattan** [comment]
Hmm yeah I tried it with the "VR Presentation".  For some reason, the Vive keeps wanting to display something that looks like an white air-hanger room.  I tried enrolling in Steam Beta mode but it didn't seem to fix it.  I also tried having Steam VR running before and after starting chrome.

The video output of the Vive doesn't seem to be catching what is in the browser though.  Any other ideas?

**Comment by capnmidnight** [comment]
You don't happen to also have an Oculus Rift plugged in, do you?
On Jun 2, 2016 5:46 PM, "alexiskattan" <notifications@github.com> wrote:

Hmm yeah I tried it with the "VR Presentation". For some reason, the Vive
keeps wanting to display something that looks like an white air-hanger
room. I tried enrolling in Steam Beta mode but it didn't seem to fix it. I
also tried having Steam VR running before and after starting chrome.

The video output of the Vive doesn't seem to be catching what is in the
browser though. Any other ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/toji/chrome-webvr-issues/issues/69#issuecomment-223432649>,
or mute the thread
<https://github.com/notifications/unsubscribe/AASMPjBreWiDUNz0OT6bVDWIWL7w8Eo6ks5qH083gaJpZM4IsZp->
.

**Comment by alexiskattan** [comment]
No it is just the HTC Vive.  Is there a debug I can copy and paste?

Or is there a way to "set" SteamVR to point to the browser?

**Comment by ClintChil** [comment]
@alexiskattan Have you tried this? Quit SteamVR before you launch the Chrome WebVR build. Then load the [VR Presentation](https://toji.github.io/webvr-samples/03-vr-presentation.html). Do you see the 'Enter VR (E)' button?  
![](https://c2.staticflickr.com/8/7340/27149399070_eb5003d1b7_m_d.jpg)

**Comment by lcb931023** [comment]
Ran into the same issue. That Enter VR button worked for me

**Comment by Avnerus** [comment]
Just sharing my conclusions with Vive. I had a very strange output from the WebVR demos and my own project using Three.JS.
![webvr](https://cloud.githubusercontent.com/assets/39962/18127786/33304498-6f8b-11e6-8638-73b7e3f0f326.png)

But I noticed that the A-Frame demos worked fine, so after comparing the code I realized it was a missing **alpha: true** parameter when creating the WebGLRenderer. So something like: 
```
this.renderer = new THREE.WebGLRenderer({antialias: true, alpha: true});
```

**Comment by toji** [comment]
That's a valuable price of information. Thank you!

**Comment by phtaylor** [comment]
For users who are having trouble getting the WebVR demos working on their HMDs, I also responded to another related issue here: https://github.com/toji/chrome-webvr-issues/issues/94

**Comment by hamishtodd1** [comment]
I'm another person with this problem. Intriguing twist that others may or may not have: if I start steamvr, then webvr (and yes indeed I am only looking at the samples ;P), it says "webvr supported, but no vrdisplays found". But if I start webvr without steamVR, it doesn't do that - in fact, it starts tracking. I even have the "enter VR" button, but when I press it it just makes it stereo - but it just doesn't appear in the headset.

If I then start steamVR, I can get my hand controllers in there too - but it's still just the default room in the headset. If I refresh the page, it continues to work like this.

(Also phtaylor's solution sounded promising but my nvidia panel looks more like the Alek214 post in that thread)

**Comment by phtaylor** [comment]
There is a tool I found on a users computer to run Vive through the Rift drivers. I *think* it was Revive (https://github.com/LibreVR/Revive)

WebVR Would simply not display on the Vive until it was uninstalled, then things worked fine. 

Something to check for on systems you are having trouble with....

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
