### ISSUE TITLE
Photo-sphere disappears when in VR mode and not looking at it.

### ISSUE THREAD

**Issue by Milun** [toji/chrome-webvr-issues#70]
Hello,

We're working on a simple web-based VR implementation (which makes use of polyfill). At the moment, we have a 3D photo-sphere with a 2D texture applied to it, as well as a 3D model in our scene for testing:

![vrscene](https://cloud.githubusercontent.com/assets/5328426/15767542/2eade762-298c-11e6-9907-b22b6f5854de.png)

However, when we switch to VR mode (either on an Android or in Google Chrome's Android simulator), the Photo-sphere disappears:

![vrscene2](https://cloud.githubusercontent.com/assets/5328426/15767618/e4a9b3a2-298c-11e6-9f15-ca75ae064de2.png)

Upon switching to VR mode, the console gets populated nonstop with:

[.CommandBufferContext]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: Source and destination textures of the draw are the same.
[.CommandBufferContext]RENDER WARNING: Render count or primcount is 0.

The weird thing is, the Photo-sphere DOES re-appear if the view is looking at the 3D computer model. As soon as that model leaves the view, the sphere disappears. I don't know if it helps, but the Sphere is a custom .obj model which just has inwards facing models.

Is there any way to fix this? Help would be greatly appreciated, thank you!

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
