### ISSUE TITLE
Unable to load Chrome DLL

### ISSUE THREAD

**Issue by danieldunderfelt** [toji/chrome-webvr-issues#71]
The Chromium build doesn't run. It only creates an error log with the following:

```
[0611/114119:ERROR:main_dll_loader_win.cc(125)] Failed to load Chrome DLL from C:\Users\Daniel\apps\chromium_webvr_v1_win64\Chrome-bin\53.0.2744.0\chrome.dll: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xE1)
```

That's for the first try. Subsequent runs give this error:

```
[0611/114613:ERROR:main_dll_loader_win.cc(125)] Failed to load Chrome DLL from C:\Users\Daniel\apps\chromium_webvr_v1_win64\Chrome-bin\53.0.2744.0\chrome.dll: The specified module could not be found. (0x7E)
```

Running it as admin has no effect. My antivirus (Avast) doesn't flag it as a virus, either.

**Comment by toji** [comment]
This definitely sounds like the antivirus being overzealous and blocking the executable, probably because it's not from Google officially. I'm not sure how much I can do about that until the feature makes it's way into stable Chrome builds.

**Comment by namel** [comment]
I'm also getting this, with Windows Defender Real-Time Protection.  Maybe worth mentioning in the "READ ME FIRST!" file ...

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
