### ISSUE TITLE
Audio broken on htc vive for some webvr enabled sites

### ISSUE THREAD

**Issue by mrLoganite** [toji/chrome-webvr-issues#72]
Steps to reproduce

Start steamvr
Open chromium experimental and go to www.playcanvas.com and access any games and none will produce audio through htc vive headphone jack
However open another tab say to non webvr site like youtube and audio plays fine 

, also running play canvas on current versions of chrome works fine and outputs to htc vive audio jack so its looks like just the experimental is broken for some sites

**Comment by tbalouet** [comment]
I participate in this issue to say that on the Oculus Rift, the sound is not playing by default in the headset audio system, but plays instead on the regular canal, when playing WebVR experiences. 
I think it might be coming from the same bug.

**Comment by mrLoganite** [comment]
My original issue was simply that the codec for MP3 is not present in chrome experimental
