### ISSUE TITLE
Vive: resizing the canvas after a short delay doesn't work

### ISSUE THREAD

**Issue by zazabe** [toji/chrome-webvr-issues#75]
When the device is presenting, the canvas will not be correctly resized (`renderWidth*2`, `renderHeight`) if the resize is delayed. 

how to reproduce:
- in [03-vr-presentation](https://github.com/toji/webvr-samples) demo, replace [this line](https://github.com/toji/webvr-samples/blob/gh-pages/03-vr-presentation.html#L137) by `setTimeout(onResize, 1000);`:  
  ![vive-wrong-canvas-size](https://cloud.githubusercontent.com/assets/401598/16153086/205fcf8a-34a5-11e6-9aab-aa1619543621.png)

notes:
- works when SteamVR is not running
- works on Oculus Rift DK2

**Comment by zazabe** [comment]
Can be reproduced here https://zazabe.github.io/webvr-samples/03-vr-presentation.html

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
