### ISSUE TITLE
Stage parameters needs several calls to getVRDisplays() to return correct values

### ISSUE THREAD

**Issue by AurL** [toji/chrome-webvr-issues#76]
Hi, I have this issue with the HTC Vive
Scenario:

- Open chromium on https://toji.github.io/webvr-samples/05-room-scale.html
(it says: "VRDisplay reported stageParameters, but stage size was 0. Using default size.")
- Switch to VR

The camera is on the floor.
Looking closer, the stage size is actually 0 for X and Z and the sittingToStandingTransform is identity.

Calling getVRDisplays() several times after that returns the good values. Reloading the page also fixes

Also: https://jsfiddle.net/2kaueyfx/6/

![image](https://cloud.githubusercontent.com/assets/4066133/16200221/bc85f66e-370c-11e6-90dc-bc1dcb9c0936.png)

**Comment by toji** [comment]
Yup, this is a known issue and has been for a while. I think I should be able to get it fixed in the next week or two though. In the meantime if the camera ends up on the floor refreshing the pages *usually* fixes it.

**Comment by toji** [comment]
Latest build fixes this. Still may not initialize with the right values, but the right ones will be pushed to the StageParameters when they become available.
