### ISSUE TITLE
Unable to reach 90 FPS in WebVR demos with Vive.

### ISSUE THREAD

**Issue by brochington** [toji/chrome-webvr-issues#80]
I am no longer able to run WebVR demos at 90FPS through my Vive. I am able to run SteamVR games at the normal 90FPS. 

Details:
OS: Windows 10
Chrome WebVR build: June 30th build.

Below is an image of the "Room Scale" demo found on webvr.info running around 60FPS. Please also note the dropped frames that are indicated in the SteamVR settings panel
![missed_frames_2](https://cloud.githubusercontent.com/assets/3392188/16570184/adee1994-41f5-11e6-81be-e6e71c478564.PNG)

Here is my SteamVR generated system report.
[webvr_sys_report.txt](https://github.com/toji/chrome-webvr-issues/files/346851/webvr_sys_report.txt)

I've also noticed that chrome is generatinga debug file on my exiting: 

[chromium_debug.txt.txt](https://github.com/toji/chrome-webvr-issues/files/346855/chromium_debug.txt.txt)

I don't recall the exact last build that works for me at 90FPS, but I'm pretty sure it was a 52.x of Chromium. 

Please let me know if their is anything I can do to help debug this, including any other details of my system.

**Comment by sminnee** [comment]
Are you `vrDisplay.requestAnimationFrame` instead of `window.requestAnimationFrame`, where `vrDisplay` is set by something like this?

    navigator.getVRDisplays().then(function(displays) {
      if (displays.length > 0) {
        vrDisplay = displays[0];
      }
    });

This is what I had to do in order to get 90FPS

**Comment by brochington** [comment]
@sminnee The demo that is running slow is provided by the webvr.info page. That particular demo has run @90FPS in the past, and I assume that it is using code similar to that which you posted.

**Comment by toji** [comment]
I heard from a separate issue that NVIDIA drivers may interfere with WebVR is they have vsync forcibly enabled for Chrome via the NVIDIA control panel. This seems to be a bigger problem for OpenGL apps, which WebVR Chromium currently is. Can you check and see if that's the case here?

**Comment by brochington** [comment]
@toji Had a little time today to troubleshoot this some more, and it does look related to NVIDIA drivers (for my 970GTX). I had reset my dev box, which defaulted to older NVIDIA drivers. These older drivers allowed me to get to 90FPS.

I've had some luck playing around with a couple things, and I've been able to reach 90FPS again (phew!) with the latest NVIDIA drivers and your latest build (July 29).  My workaround is to go into the NVIDIA control panel -> Manage 3D settings, and click "Restore". I do not need to change any settings, and I haven't noticed any settings change after I do this. V-sync is "On". After I do this I can usually get to 90FPS on my Gsync enabled monitor, but not always on my regular 1080p monitor. I will try to fuss with these settings more soon, but for now they get me through this blocker.

Let me know if their is any specific testing/data that you would like from me.

**Comment by gormanj** [comment]
Same here on Vive. If anyone can post a link to a version of the browser that hits 90 fps, I need it only for sketchfab for a demo tomorrow.

Brochington> are you saying you think V-sync needed to be on? I kind of thought that it is always on and cannot be disabled for VR. Do you think there is some other setting that is getting you the 90 again?

Toji > Is there a version of NVIDIA driver that you suggest we try to roll back to?

Thank you all.

**Comment by brochington** [comment]
@gormanj It has been awhile since I've last tried, but if my memory serves me correctly, I just needed to restore the settings as explained above.

**Comment by campmdabt** [comment]
You do need vsync to be forced OFF to hit 90 FPS. I had the same issue with capping at 60 Hz and when I came across this post I thought duh. A setting of ON will sync the frame rate with the refresh rate of your monitor (most are 60 Hz) instead of the headset.

Go into your NVIDIA Control Panel -> 3D Settings -> Manage 3D settings, and either set the 
Global Settings" tab "Vertical sync" option to "Off" (not recommended since that's across your entire machine), or go to the "Program Settings" tab, in the selection box select "Google Chrome" for the chromium build (or whatever program you're using for webvr) and change the "Vertical sync" option to "Off" and hit apply. This will disable vsync just for that program. If the program is open, make sure you restart it for the settings to take effect.

Uncapped my FPS from 60 to 90 immediately.

![capture](https://cloud.githubusercontent.com/assets/15316009/20548848/fd14fc22-b0f4-11e6-89d5-c259c33b31e5.JPG)

**Comment by gormanj** [comment]
Thank you very much for the help.

**Comment by campmdabt** [comment]
Hey, just glad I could give back to the community in some small way.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
