### ISSUE TITLE
VRPose timestamp property name casing different in WebVR spec versus Chromium implementation.

### ISSUE THREAD

**Issue by capnmidnight** [toji/chrome-webvr-issues#82]
The WebVR spec has the the `timestamp` property in all lower case:  https://github.com/w3c/webvr/blob/gh-pages/index.idl#L77

As of the Jul 11 build, Chromium shows this property as `timeStamp`.

This should probably be the all-lowercase version to remain consistent with other Web API's usage of the term in other classes.

**Comment by cvan** [comment]
FWIW, the Gamepad API calls it [`timestamp`](https://w3c.github.io/gamepad/#widl-Gamepad-timestamp).

**Comment by toji** [comment]
This is fixed in either the current build or the one before it, I just forgot to note it.
