### ISSUE TITLE
AMD and Webvr Chrome with Vive?

### ISSUE THREAD

**Issue by SBUtltmedia** [toji/chrome-webvr-issues#83]
Hello,
I was wondering if anyone WebVR working using AMD video cards.

**Comment by capnmidnight** [comment]
Yes, I have done some testing on a machine with a Vive and an AMD GPU. I
had to disable the GPU blacklist in chrome://flags to get it to work.

**Comment by dddExperiments** [comment]
@capnmidnight : it seems that a bunch of us are having isssues with AMD card in this thread https://github.com/toji/chrome-webvr-issues/issues/64

I've disabled the GPU blacklist too but it's not enough for me to run the samples (see other thread).
Do you have any other tip to run webvr with chromium and AMD card?
Can you post your about:gpu or check my screenshot for obvious issues in the other thread?

Thanks!

**Comment by capnmidnight** [comment]
I don't have an AMD GPU anymore, I'm on an NVidia GTX 1070 now :stuck_out_tongue:

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
