### ISSUE TITLE
VRPose linearAcceleration and angularAcceleration are null on Vive

### ISSUE THREAD

**Issue by jbaicoianu** [toji/chrome-webvr-issues#84]
It looks like the linearAcceleration and angularAcceleration data isn't being populated in VRPose data, both for the HMD and the controllers when using Vive.  These properties always return null on the Vive, whereas on the Rift they return proper vectors.

Seems the OpenVR API should be exposing them::
linearAcceleration: https://github.com/ValveSoftware/openvr/blob/b20b25705d8dd82be221fe68a61db36ae7e2608e/headers/openvr_driver.h#L1388-L1389
angularAcceleration: https://github.com/ValveSoftware/openvr/blob/b20b25705d8dd82be221fe68a61db36ae7e2608e/headers/openvr_driver.h#L1400-L1404

I was planning on doing some experiments with the accelerometer information from the controllers, eg being able to shake them to control things in the world. I could derive this data from the velocity over time (which the driver apparently does for angular acceleration anyway) but it would be great it we could read it directly.

**Comment by toji** [comment]
Thanks for the links, but that's from the driver implementation interface, which I don't have access to. The pose that gets exposed to applications is [TrackedDevicePose_t](https://github.com/ValveSoftware/openvr/blob/b20b25705d8dd82be221fe68a61db36ae7e2608e/headers/openvr_driver.h#L171), which as you can see doesn't contain any acceleration data. Sorry!

It may be reasonable for WebVR to derive this from the velocity for you if it's not provided by the underlying API. I'll have to look into that.

**Comment by brianchirls** [comment]
I was just looking into this myself a couple days ago. That stuff could, in theory, be derived either under the webvr hood or in javascript.

@toji I'm curious if you have a particular algorithm in mind?

**Comment by toji** [comment]
Not at the moment. Wouldn't turn down a link or two is someone has a good method in mind.

**Comment by jbaicoianu** [comment]
Ahh, yeah that's what I was worried about.  I wouldn't bother putting it in on the WebVR side of things - Valve should expose it, and in the meantime we can just derive over time in our apps.  

There's already an open issue on the OpenVR github - https://github.com/ValveSoftware/openvr/issues/75

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
