### ISSUE TITLE
Presentation to re-connected display does not work

### ISSUE THREAD

**Issue by brianchirls** [toji/chrome-webvr-issues#85]
To replicate:
1. Load a sample page with an HMD connected
2. `requestPresent` on that HMD
3. Unplug or turn off the HMD without calling `exitPresent`
4. Turn HMD back on
5. `requestPresent` on that HMD again

Pose tracking works on the re-connected HMD, but the display shows nothing.

**Comment by brianchirls** [comment]
BTW, I tested this with Oculus Rift DK2. I'm aware Vive support for display connection events is in progress.

**Comment by brianchirls** [comment]
I just checked up on this, and it seems to be working fine now. But I'll let someone else confirm before closing.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
