### ISSUE TITLE
Not correctly detecting displays at start up

### ISSUE THREAD

**Issue by brianchirls** [toji/chrome-webvr-issues#86]
To replicate:
1. Plug in and turn on HMD before browser is started
2. Load a WebVR page
3. Disconnect HMD (`vrdisplayconnected` event fires correctly)
4. Reload the same WebVR page

The disconnected HMD will show up in array returned from `navigator.getVRDisplays()`.

Similarly, if you start the browser with an HMD disconnected and then connect that HMD, `vrdisplayconnected` event will not fire once the HMD is connected. However, if you run `navigator.getVRDisplays()` again later, the HMD will show up.

Again, tested with Oculus Rift DK2

**Comment by brianchirls** [comment]
I'm aware @toji  is very busy with other things right now, but for the record, this is still an issue as of the August 28th version.

By the way, `isConnected` is `true` on the device in question, which is incorrect.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
