### ISSUE TITLE
Chaperone bounds show early with VIVE

### ISSUE THREAD

**Issue by caseyyee** [toji/chrome-webvr-issues#87]
Not sure why this is, but it seems that I run into the chaperone bounds much earlier with WebVR scenes than with any native experiences I've seen.

**Comment by toji** [comment]
I can't imagine why that would be, as Chrome doesn't do anything with Chaperone. It's driven entirely by Valve's service.

Two theories:

1) It's a placebo effect, possibly brought on by the lag between the chaperone and the WebVR scene.
2) The WebVR scene in question has the scale subtly off so that you feel like you're moving less than you actually are when you walk around.

:( I'm not sure if there's any quantifiable way to show if this is actually happening or not.

**Comment by cvan** [comment]
I've also seen this. Even with https://toji.github.io/webvr-samples/05-room-scale.html. But with that test scene, it's actually difficult to discern where the stage is supposed to actually be. We should have a clear test case (and probably link to it from [IsWebVRReady.org](https://iswebvrready.org/) and [the spec](https://w3c.github.io/webvr/)).

**Comment by AgentME** [comment]
Are you sure that you didn't leave either of the controllers turned on and near or outside of the bounds? I had this exact problem while playing a (regular VR non-webvr) game that only needed one controller. I had set the other controller down out of bounds which meant that the chaperone bounds were constantly visible.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
