### ISSUE TITLE
Crash for large facet/triangle count

### ISSUE THREAD

**Issue by cadnexus** [toji/chrome-webvr-issues#88]
Recently we have been loading fairly large CAD models with triangle counts ranging from 3-10 million. ~3 million works great in Chrome (54.0.2812.0) + Vive/Oculus, but anything above that crashes the browser. We have pushed firefox nightly to ~10 million triangles. 

The message I see is "chromium ran out of memory while displaying this page" Is there a cache or setting limiting memory use of Chrome ? Is there a way to generate a debug log file I can post ?

Thanks.
-Ali

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
