### ISSUE TITLE
Vive Controllers not showing up for navigation

### ISSUE THREAD

**Issue by eigertiger** [toji/chrome-webvr-issues#89]
Can navigate my scene with the Vive Controllers. The example scene that demonstrated navigation worked however

**Comment by capnmidnight** [comment]
Movement doesn't come for free. You have to read the gamepad state, figure out from the position and orientation where there user is pointing, figure out from the button state when they clicked a button. With that information, you then have to figure out update the view.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
