### ISSUE TITLE
75 FPS

### ISSUE THREAD

**Issue by pyalot** [toji/chrome-webvr-issues#9]
The Oculus DK2 runs at 75 FPS. I'm not sure the chrome build reaches that framerate, it's a possible issue.

**Comment by capnmidnight** [comment]
I've also had good luck with setting my primary display to a display mode that supports 75hz. The resolution is lower than the native LCD resolution, so it's a little annoying, but it's been easier to wrangle than making the Rift the primary display.

**Comment by toji** [comment]
Update: With the 1.0 API VR-specific refresh rates are now provided by `VRDisplay.requestAnimationFrame()`, which should make getting the right framerate a lot more reliable. The current build doesn't implement this behavior completely correctly just yet, however, so I'm leaving the issue open.

**Comment by davidknag** [comment]
having downloaded the executable, enabled webvr in about:flags, i get 30fps in chrome with an intel 4790k and nvidia gtx 980. It's unusable, but promising

**Comment by toji** [comment]
@davidknag: With specs like that you should easily be getting 75 or 90hz, so I suspect something external to the browser is causing issues. Are you maybe ripping Blu-ray disks in the background or something? :) (More realistically, do you run antivirus? That can be a big perf killer).

**Comment by davidknag** [comment]
task manager has all stats under 50%, no apps using excessive cpu, i get 75fps in virtual desktop, not too interested in making it work, just wanted to report my prefs. Seems to cap the framerate at 30, though i did see it jump to 35 once. It could be because i'm running the polyfills and it's drawing to my monitor as well because the regular demos don't run on my rift. "Sorry we're having trouble loading chrome.exe" is shown in the rift after i hover over the warning.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
