### ISSUE TITLE
Unable to play mp4/mov on html5 video element

### ISSUE THREAD

**Issue by vellow** [toji/chrome-webvr-issues#90]
In my case, I use html5 video as texture, but failed to play on this build..

e.g. 
`<video src="./img/v_cube.mp4" controls="true"></video>`

**Comment by toji** [comment]
These builds are Chromium, not Chrome. I don't have the license to redistribute decoders for patent-encumbered formats, so they are not included in the WebVR experimental builds. This problem will go away once I can get WebVR officially landed in Chrome.
