### ISSUE TITLE
Ultra-slow getPose() with VIVE on some machines but not others

### ISSUE THREAD

**Issue by bhouston** [toji/chrome-webvr-issues#92]
(Posted this to the webvr mailing list but copying here for reference.)

We are running into a situation where we are getting a very slow
getPose() in our WebVR stuff with the VIVE but only on some machines,
on others it operates perfectly.

They seem nearly identical but there are likely differences.  Both are
running NVIDIA GeForce 980s with the latest driver and running the
same latest build of Chromium WebVR browser.

Basically we have a test page here: http://exocortex.github.io/vr

I have a captured from the Chrome profiler showing the speed issue
here - 400ms per getPose() calls:

https://www.dropbox.com/s/anrvz28uec3su8l/CPU-20160831T101518.cpuprofile?dl=0

Interestingly, we are using the ThreeJS VRControls, and the latest
ThreeJS VR demo that use this code do not exhibit it on the
problematic machines.  Sketchfab's VR stuff also doesn't exhibit this
behavior.  I have confirmed that Sketchfab's VR code is very similar
and relies upon getPose as well.

Thus I am starting to think there is an order of operations issue at
play that is interacting with machine specific setups?  Could there be
VIVE SDK versions at play?  But it is still weird it affects our VR
and not the ThreeJS VR demos.

I guess our next step is to try and do a binary search of the
differences between our usage and the ThreeJS VR demos until we find
the change that causes this.

**Comment by bhouston** [comment]
Likely related to underlying OpenVR calls discussed here: https://steamcommunity.com/app/358720/discussions/0/405691491122676152/

**Comment by bhouston** [comment]
More discussion here: https://github.com/ValveSoftware/openvr/issues/64

**Comment by bhouston** [comment]
Should we try to attach a C++ profiler to the Chromium WebVR browser when this is happening?  I guess that Chromium WebVR build doesn't have debug info so we'd have to build it ourselves.  Does anyone have a Chromium WebVR debug build around we can use for this purpose?

**Comment by bhouston** [comment]
To be clear, we have three machines where this is always reproducible and a bunch of other machine where it never happens.  Thus we have a reproduction case -- although it is at a customer site, and not at our office.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
