### ISSUE TITLE
Remote desktop with webvr enabled causes WebGL to be disabled

### ISSUE THREAD

**Issue by bhouston** [toji/chrome-webvr-issues#93]
When running on Windows 10 with a real GPU, it is possible to remote desktop in via the RDP protocol and run WebGL applications in that session in Chrome.  IT works and works well.

But if I enable WebVR via the chrome://flags then WebGL does not initialize properly, the gl context is null.

This is not a limitation of the VIVE/OpenVR SDK because I can play steam games and the Google Tilt BRush application over the RDP sessions -- I just put on the helmet and it displays properly. 

So this is a limitation likely of something inside of Chromium.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
