### ISSUE TITLE
Forcing renderTargetMultiplier breaks VR experience

### ISSUE THREAD

**Issue by mflux** [toji/chrome-webvr-issues#95]
So this article seemed pretty popular, people enable it to force supersampling on their VR games:

http://www.roadtovr.com/how-to-improve-your-htc-vive-image-quality-with-supersampling-pixel-density-tweak/

However, enabling this wrecks WebVR right now. I'm not certain if the build is at fault, or the JS that splits the stereo effect is at fault.

See above article to enable renderTargetMultiplier then open a Webvr project to reproduce.

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
