### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by arthurjamain** [toji/chrome-webvr-issues#96]
Hey there !

I am currently trying to build chromium on windows using the WebVR code that you published. I obviously ran into a lot of issues, given that I'm not really familiar with the build process as a whole, but eventually succeeded in getting all the tools and building a standard version of chromium.

I now need to integrate the WebVR code into this build, and have been running into various issues. Rather than posting long stack traces that probably won't help much since I'm probably making basic mistakes, I would very much appreciate if someone could answer these few questions that would probably help set me back on tracks. Sorry if they sound dumb or obvious.
- Is the code found at https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_1 a complete checkout ? Should I be able to build it directly, or should I merge it into a main branch of chromium (which seems to be the case) ?
- If so, is there a specific branch / family of branches that I should target ?
- Are there maybe changes to be made to DEPS that are necessary for the code to run ? (I'm looking at skia specifically here, which for some reason is trying to checkout on a commit that doesn't seem to exist, or at least is inaccessible to me)

So far I've tried checking out chromium @ 55 then merged the contents of your repo into it, then could not get past gclient sync which tripped on skia repeatedly.

I believe it is too soon for me to be asking more specific questions on why my process is failing, but I would very much like to know if it's at least doable from an average joe's workstation and if I'm on the right track.

Thanks for reading and for your work in general !

-- Arthur J, front @ Sketchfab

P.S. : FWIW, my motive is that we're trying to build a native app which has WebVR capabilities.

**Comment by toji** [comment]
Not a dumb question at all! The build process for any project this size is always a bit obtuse and slightly magical. :P Makes it hard to grok what steps need to happen in what order for newcomers.

If you checkout the code at https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr_1 and run `gclient sync` to ensure the dependencies are at the right version it should be buildable as-is without rebasing onto the current top of tree.

**Comment by arthurjamain** [comment]
Great news :) I'll give it another shot tonight. Thanks for the quick answer !

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
