### ISSUE TITLE
Gamepad-extensions flags revert to Default

### ISSUE THREAD

**Issue by arturitu** [toji/chrome-webvr-issues#98]
I'm not sure if is a issue. But if you set as 'enabled' Gamepad-extensions on flags on the 17 Sept version, and after you open a previous version of Chromium (29 Aug in my case), 'Gamepad-extensions' reverted to 'Default'.

**Comment by toji** [comment]
That's the expected behavior. The flag didn't exist in the previous version, so when those flags save it gets wiped out. Thanks for the report, though!
