### ISSUE TITLE
Support OSVR in Chromium?

### ISSUE THREAD

**Issue by shaoboyan** [toji/chrome-webvr-issues#99]
Just receive the post from Sensics (http://sensics.com/why-webvr/)

"A few days ago, Microsoft announced that they are starting development on experimental WebVR support in Microsoft Edge. OSVR supports WebVR in Mozilla Firefox and we hope to carry this support over to Edge."

Since OSVR has positive attitudes on Web, Is it possible to support OSVR in chromium as a hardware abstract layer?

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
